const POKEMON_DATABASE = [
    { name: "フシギダネ", gen: 1, types: ["くさ", "どく"] },
    { name: "フシギソウ", gen: 1, types: ["くさ", "どく"] },
    { name: "フシギバナ", gen: 1, types: ["くさ", "どく"] },
    { name: "メガフシギバナ", gen: "メガシンカ", types: ["くさ", "どく"] },
    { name: "フシギバナ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["くさ", "どく"] },
    { name: "ヒトカゲ", gen: 1, types: ["ほのお"] },
    { name: "リザード", gen: 1, types: ["ほのお"] },
    { name: "リザードン", gen: 1, types: ["ほのお", "ひこう"] },
    { name: "メガリザードンX", gen: "メガシンカ", types: ["ほのお", "ドラゴン"] },
    { name: "メガリザードンY", gen: "メガシンカ", types: ["ほのお", "ひこう"] },
    { name: "リザードン(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ほのお", "ひこう"] },
    { name: "ゼニガメ", gen: 1, types: ["みず"] },
    { name: "カメール", gen: 1, types: ["みず"] },
    { name: "カメックス", gen: 1, types: ["みず"] },
    { name: "メガカメックス", gen: "メガシンカ", types: ["みず"] },
    { name: "カメックス(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["みず"] },
    { name: "キャタピー", gen: 1, types: ["むし"] },
    { name: "トランセル", gen: 1, types: ["むし"] },
    { name: "バタフリー", gen: 1, types: ["むし", "ひこう"] },
    { name: "バタフリー(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["むし", "ひこう"] },
    { name: "ビードル", gen: 1, types: ["むし", "どく"] },
    { name: "コクーン", gen: 1, types: ["むし", "どく"] },
    { name: "スピアー", gen: 1, types: ["むし", "どく"] },
    { name: "メガスピアー", gen: "メガシンカ", types: ["むし", "どく"] },
    { name: "ポッポ", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "ピジョン", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "ピジョット", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "メガピジョット", gen: "メガシンカ", types: ["ノーマル", "ひこう"] },
    { name: "コラッタ", gen: 1, types: ["ノーマル"] },
    { name: "コラッタ(アローラのすがた)", gen: 7, types: ["あく", "ノーマル"] },
    { name: "ラッタ", gen: 1, types: ["ノーマル"] },
    { name: "ラッタ(アローラのすがた)", gen: 7, types: ["あく", "ノーマル"] },
    { name: "オニスズメ", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "オニドリル", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "アーボ", gen: 1, types: ["どく"] },
    { name: "アーボック", gen: 1, types: ["どく"] },
    { name: "ピカチュウ", gen: 1, types: ["でんき"] },
    { name: "ピカチュウ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["でんき"] },
    { name: "ライチュウ", gen: 1, types: ["でんき"] },
    { name: "メガライチュウX", gen: "メガシンカ", types: ["でんき"] },
    { name: "メガライチュウY", gen: "メガシンカ", types: ["でんき"] },
    { name: "ライチュウ(アローラのすがた)", gen: 7, types: ["でんき", "エスパー"] },
    { name: "サンド", gen: 1, types: ["じめん"] },
    { name: "サンド(アローラのすがた)", gen: 7, types: ["こおり", "はがね"] },
    { name: "サンドパン", gen: 1, types: ["じめん"] },
    { name: "サンドパン(アローラのすがた)", gen: 7, types: ["こおり", "はがね"] },
    { name: "ニドラン♀", gen: 1, types: ["どく"] },
    { name: "ニドリーナ", gen: 1, types: ["どく"] },
    { name: "ニドクイン", gen: 1, types: ["どく", "じめん"] },
    { name: "ニドラン♂", gen: 1, types: ["どく"] },
    { name: "ニドリーノ", gen: 1, types: ["どく"] },
    { name: "ニドキング", gen: 1, types: ["どく", "じめん"] },
    { name: "ピッピ", gen: 1, types: ["フェアリー"] },
    { name: "ピクシー", gen: 1, types: ["フェアリー"] },
    { name: "メガピクシー", gen: "メガシンカ", types: ["フェアリー", "ひこう"] },
    { name: "ロコン", gen: 1, types: ["ほのお"] },
    { name: "ロコン(アローラのすがた)", gen: 7, types: ["こおり"] },
    { name: "キュウコン", gen: 1, types: ["ほのお"] },
    { name: "キュウコン(アローラのすがた)", gen: 7, types: ["こおり", "フェアリー"] },
    { name: "プリン", gen: 1, types: ["ノーマル", "フェアリー"] },
    { name: "プクリン", gen: 1, types: ["ノーマル", "フェアリー"] },
    { name: "ズバット", gen: 1, types: ["どく", "ひこう"] },
    { name: "ゴルバット", gen: 1, types: ["どく", "ひこう"] },
    { name: "ナゾノクサ", gen: 1, types: ["くさ", "どく"] },
    { name: "クサイハナ", gen: 1, types: ["くさ", "どく"] },
    { name: "ラフレシア", gen: 1, types: ["くさ", "どく"] },
    { name: "パラス", gen: 1, types: ["むし", "くさ"] },
    { name: "パラセクト", gen: 1, types: ["むし", "くさ"] },
    { name: "コンパン", gen: 1, types: ["むし", "どく"] },
    { name: "モルフォン", gen: 1, types: ["むし", "どく"] },
    { name: "ディグダ", gen: 1, types: ["じめん"] },
    { name: "ディグダ(アローラのすがた)", gen: 7, types: ["じめん", "はがね"] },
    { name: "ダグトリオ", gen: 1, types: ["じめん"] },
    { name: "ダグトリオ(アローラのすがた)", gen: 7, types: ["じめん", "はがね"] },
    { name: "ニャース", gen: 1, types: ["ノーマル"] },
    { name: "ニャース(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ノーマル"] },
    { name: "ニャース(アローラのすがた)", gen: 7, types: ["あく"] },
    { name: "ニャース(ガラルのすがた)", gen: 8, types: ["はがね"] },
    { name: "ペルシアン", gen: 1, types: ["ノーマル"] },
    { name: "ペルシアン(アローラのすがた)", gen: 7, types: ["あく"] },
    { name: "コダック", gen: 1, types: ["みず"] },
    { name: "ゴルダック", gen: 1, types: ["みず"] },
    { name: "マンキー", gen: 1, types: ["かくとう"] },
    { name: "オコリザル", gen: 1, types: ["かくとう"] },
    { name: "ガーディ", gen: 1, types: ["ほのお"] },
    { name: "ガーディ(ヒスイのすがた)", gen: 8, types: ["ほのお", "いわ"] },
    { name: "ウインディ", gen: 1, types: ["ほのお"] },
    { name: "ウインディ(ヒスイのすがた)", gen: 8, types: ["ほのお", "いわ"] },
    { name: "ニョロモ", gen: 1, types: ["みず"] },
    { name: "ニョロゾ", gen: 1, types: ["みず"] },
    { name: "ニョロボン", gen: 1, types: ["みず", "かくとう"] },
    { name: "ケーシィ", gen: 1, types: ["エスパー"] },
    { name: "ユンゲラー", gen: 1, types: ["エスパー"] },
    { name: "フーディン", gen: 1, types: ["エスパー"] },
    { name: "メガフーディン", gen: "メガシンカ", types: ["エスパー"] },
    { name: "ワンリキー", gen: 1, types: ["かくとう"] },
    { name: "ゴーリキー", gen: 1, types: ["かくとう"] },
    { name: "カイリキー", gen: 1, types: ["かくとう"] },
    { name: "カイリキー(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["かくとう"] },
    { name: "マダツボミ", gen: 1, types: ["くさ", "どく"] },
    { name: "ウツドン", gen: 1, types: ["くさ", "どく"] },
    { name: "ウツボット", gen: 1, types: ["くさ", "どく"] },
    { name: "メガウツボット", gen: "メガシンカ", types: ["くさ", "どく"] },
    { name: "メノクラゲ", gen: 1, types: ["みず", "どく"] },
    { name: "ドククラゲ", gen: 1, types: ["みず", "どく"] },
    { name: "イシツブテ", gen: 1, types: ["いわ", "じめん"] },
    { name: "イシツブテ(アローラのすがた)", gen: 7, types: ["いわ", "でんき"] },
    { name: "ゴローン", gen: 1, types: ["いわ", "じめん"] },
    { name: "ゴローン(アローラのすがた)", gen: 7, types: ["いわ", "でんき"] },
    { name: "ゴローニャ", gen: 1, types: ["いわ", "じめん"] },
    { name: "ゴローニャ(アローラのすがた)", gen: 7, types: ["いわ", "でんき"] },
    { name: "ポニータ", gen: 1, types: ["ほのお"] },
    { name: "ポニータ (ガラルのすがた)", gen: 8, types: ["エスパー"] },
    { name: "ギャロップ", gen: 1, types: ["ほのお"] },
    { name: "ギャロップ(ガラルのすがた)", gen: 8, types: ["エスパー", "フェアリー"] },
    { name: "ヤドン", gen: 1, types: ["みず", "エスパー"] },
    { name: "ヤドン(ガラルのすがた)", gen: 8, types: ["エスパー"] },
    { name: "ヤドラン", gen: 1, types: ["みず", "エスパー"] },
    { name: "メガヤドラン", gen: "メガシンカ", types: ["みず", "エスパー"] },
    { name: "ヤドラン(ガラルのすがた)", gen: 8, types: ["どく", "エスパー"] },
    { name: "コイル", gen: 1, types: ["でんき", "はがね"] },
    { name: "レアコイル", gen: 1, types: ["でんき", "はがね"] },
    { name: "カモネギ", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "カモネギ(ガラルのすがた)", gen: 8, types: ["かくとう"] },
    { name: "ドードー", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "ドードリオ", gen: 1, types: ["ノーマル", "ひこう"] },
    { name: "パウワウ", gen: 1, types: ["みず"] },
    { name: "ジュゴン", gen: 1, types: ["みず", "こおり"] },
    { name: "ベトベター", gen: 1, types: ["どく"] },
    { name: "ベトベター(アローラのすがた)", gen: 7, types: ["どく", "あく"] },
    { name: "ベトベトン", gen: 1, types: ["どく"] },
    { name: "ベトベトン(アローラのすがた)", gen: 7, types: ["どく", "あく"] },
    { name: "シェルダー", gen: 1, types: ["みず"] },
    { name: "パルシェン", gen: 1, types: ["みず", "こおり"] },
    { name: "ゴース", gen: 1, types: ["ゴースト", "どく"] },
    { name: "ゴースト", gen: 1, types: ["ゴースト", "どく"] },
    { name: "ゲンガー", gen: 1, types: ["ゴースト", "どく"] },
    { name: "メガゲンガー", gen: "メガシンカ", types: ["ゴースト", "どく"] },
    { name: "ゲンガー(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ゴースト", "どく"] },
    { name: "イワーク", gen: 1, types: ["いわ", "じめん"] },
    { name: "スリープ", gen: 1, types: ["エスパー"] },
    { name: "スリーパー", gen: 1, types: ["エスパー"] },
    { name: "クラブ", gen: 1, types: ["みず"] },
    { name: "キングラー", gen: 1, types: ["みず"] },
    { name: "キングラー(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["みず"] },
    { name: "ビリリダマ", gen: 1, types: ["でんき"] },
    { name: "ビリリダマ(ヒスイのすがた)", gen: 8, types: ["でんき", "くさ"] },
    { name: "マルマイン", gen: 1, types: ["でんき"] },
    { name: "マルマイン(ヒスイのすがた)", gen: 8, types: ["でんき", "くさ"] },
    { name: "タマタマ", gen: 1, types: ["くさ", "エスパー"] },
    { name: "ナッシー", gen: 1, types: ["くさ", "エスパー"] },
    { name: "ナッシー(アローラのすがた)", gen: 7, types: ["くさ", "ドラゴン"] },
    { name: "カラカラ", gen: 1, types: ["じめん"] },
    { name: "ガラガラ", gen: 1, types: ["じめん"] },
    { name: "ガラガラ(アローラのすがた)", gen: 7, types: ["ほのお", "ゴースト"] },
    { name: "サワムラー", gen: 1, types: ["かくとう"] },
    { name: "エビワラー", gen: 1, types: ["かくとう"] },
    { name: "ベロリンガ", gen: 1, types: ["ノーマル"] },
    { name: "ドガース", gen: 1, types: ["どく"] },
    { name: "マタドガス", gen: 1, types: ["どく"] },
    { name: "マタドガス(ガラルのすがた)", gen: 8, types: ["どく", "フェアリー"] },
    { name: "サイホーン", gen: 1, types: ["じめん", "いわ"] },
    { name: "サイドン", gen: 1, types: ["じめん", "いわ"] },
    { name: "ラッキー", gen: 1, types: ["ノーマル"] },
    { name: "モンジャラ", gen: 1, types: ["くさ"] },
    { name: "ガルーラ", gen: 1, types: ["ノーマル"] },
    { name: "メガガルーラ", gen: "メガシンカ", types: ["ノーマル"] },
    { name: "タッツー", gen: 1, types: ["みず"] },
    { name: "シードラ", gen: 1, types: ["みず"] },
    { name: "トサキント", gen: 1, types: ["みず"] },
    { name: "アズマオウ", gen: 1, types: ["みず"] },
    { name: "ヒトデマン", gen: 1, types: ["みず"] },
    { name: "スターミー", gen: 1, types: ["みず", "エスパー"] },
    { name: "メガスターミー", gen: "メガシンカ", types: ["みず", "エスパー"] },
    { name: "バリヤード", gen: 1, types: ["エスパー", "フェアリー"] },
    { name: "バリヤード(ガラルのすがた)", gen: 8, types: ["こおり", "エスパー"] },
    { name: "ストライク", gen: 1, types: ["むし", "ひこう"] },
    { name: "ルージュラ", gen: 1, types: ["こおり", "エスパー"] },
    { name: "エレブー", gen: 1, types: ["でんき"] },
    { name: "ブーバー", gen: 1, types: ["ほのお"] },
    { name: "カイロス", gen: 1, types: ["むし"] },
    { name: "メガカイロス", gen: "メガシンカ", types: ["むし", "ひこう"] },
    { name: "ケンタロス", gen: 1, types: ["ノーマル"] },
    { name: "ケンタロス(パルデアのすがた・コンバットしゅ)", gen: 9, types: ["かくとう"] },
    { name: "ケンタロス(パルデアのすがた・ブレイズしゅ)", gen: 9, types: ["かくとう", "ほのお"] },
    { name: "ケンタロス(パルデアのすがた・ウォーターしゅ)", gen: 9, types: ["かくとう", "みず"] },
    { name: "コイキング", gen: 1, types: ["みず"] },
    { name: "ギャラドス", gen: 1, types: ["みず", "ひこう"] },
    { name: "メガギャラドス", gen: "メガシンカ", types: ["みず", "あく"] },
    { name: "ラプラス", gen: 1, types: ["みず", "こおり"] },
    { name: "ラプラス(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["みず", "こおり"] },
    { name: "メタモン", gen: 1, types: ["ノーマル"] },
    { name: "イーブイ", gen: 1, types: ["ノーマル"] },
    { name: "イーブイ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ノーマル"] },
    { name: "シャワーズ", gen: 1, types: ["みず"] },
    { name: "サンダース", gen: 1, types: ["でんき"] },
    { name: "ブースター", gen: 1, types: ["ほのお"] },
    { name: "ポリゴン", gen: 1, types: ["ノーマル"] },
    { name: "オムナイト", gen: 1, types: ["いわ", "みず"] },
    { name: "オムスター", gen: 1, types: ["いわ", "みず"] },
    { name: "カブト", gen: 1, types: ["いわ", "みず"] },
    { name: "カブトプス", gen: 1, types: ["いわ", "みず"] },
    { name: "プテラ", gen: 1, types: ["いわ", "ひこう"] },
    { name: "メガプテラ", gen: "メガシンカ", types: ["いわ", "ひこう"] },
    { name: "カビゴン", gen: 1, types: ["ノーマル"] },
    { name: "カビゴン(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ノーマル"] },
    { name: "フリーザー", gen: 1, types: ["こおり", "ひこう"] },
    { name: "フリーザー(ガラルのすがた)", gen: 8, types: ["エスパー", "ひこう"] },
    { name: "サンダー", gen: 1, types: ["でんき", "ひこう"] },
    { name: "サンダー(ガラルのすがた)", gen: 8, types: ["かくとう", "ひこう"] },
    { name: "ファイヤー", gen: 1, types: ["ほのお", "ひこう"] },
    { name: "ファイヤー(ガラルのすがた)", gen: 8, types: ["あく", "ひこう"] },
    { name: "ミニリュウ", gen: 1, types: ["ドラゴン"] },
    { name: "ハクリュー", gen: 1, types: ["ドラゴン"] },
    { name: "カイリュー", gen: 1, types: ["ドラゴン", "ひこう"] },
    { name: "メガカイリュー", gen: "メガシンカ", types: ["ドラゴン", "ひこう"] },
    { name: "ミュウツー", gen: 1, types: ["エスパー"] },
    { name: "メガミュウツーX", gen: "メガシンカ", types: ["エスパー", "かくとう"] },
    { name: "メガミュウツーY", gen: "メガシンカ", types: ["エスパー"] },
    { name: "ミュウ", gen: 1, types: ["エスパー"] },
    { name: "チコリータ", gen: 2, types: ["くさ"] },
    { name: "ベイリーフ", gen: 2, types: ["くさ"] },
    { name: "メガニウム", gen: "メガシンカ", types: ["くさ"] },
    { name: "メガメガニウム", gen: "メガシンカ", types: ["くさ", "フェアリー"] },
    { name: "ヒノアラシ", gen: 2, types: ["ほのお"] },
    { name: "マグマラシ", gen: 2, types: ["ほのお"] },
    { name: "バクフーン", gen: 2, types: ["ほのお"] },
    { name: "バクフーン(ヒスイのすがた)", gen: 8, types: ["ほのお", "ゴースト"] },
    { name: "ワニノコ", gen: 2, types: ["みず"] },
    { name: "アリゲイツ", gen: 2, types: ["みず"] },
    { name: "オーダイル", gen: 2, types: ["みず"] },
    { name: "メガオーダイル", gen: "メガシンカ", types: ["みず", "ドラゴン"] },
    { name: "オタチ", gen: 2, types: ["ノーマル"] },
    { name: "オオタチ", gen: 2, types: ["ノーマル"] },
    { name: "ホーホー", gen: 2, types: ["ノーマル", "ひこう"] },
    { name: "ヨルノズク", gen: 2, types: ["ノーマル", "ひこう"] },
    { name: "レディバ", gen: 2, types: ["むし", "ひこう"] },
    { name: "レディアン", gen: 2, types: ["むし", "ひこう"] },
    { name: "イトマル", gen: 2, types: ["むし", "どく"] },
    { name: "アリアドス", gen: 2, types: ["むし", "どく"] },
    { name: "クロバット", gen: 2, types: ["どく", "ひこう"] },
    { name: "チョンチー", gen: 2, types: ["みず", "でんき"] },
    { name: "ランターン", gen: 2, types: ["みず", "でんき"] },
    { name: "ピチュー", gen: 2, types: ["でんき"] },
    { name: "ピィ", gen: 2, types: ["フェアリー"] },
    { name: "ププリン", gen: 2, types: ["ノーマル", "フェアリー"] },
    { name: "トゲピー", gen: 2, types: ["フェアリー"] },
    { name: "トゲチック", gen: 2, types: ["フェアリー", "ひこう"] },
    { name: "ネイティ", gen: 2, types: ["エスパー", "ひこう"] },
    { name: "ネイティオ", gen: 2, types: ["エスパー", "ひこう"] },
    { name: "メリープ", gen: 2, types: ["でんき"] },
    { name: "モココ", gen: 2, types: ["でんき"] },
    { name: "デンリュウ", gen: 2, types: ["でんき"] },
    { name: "メガデンリュウ", gen: "メガシンカ", types: ["でんき", "ドラゴン"] },
    { name: "キレイハナ", gen: 2, types: ["くさ"] },
    { name: "マリル", gen: 2, types: ["みず", "フェアリー"] },
    { name: "マリルリ", gen: 2, types: ["みず", "フェアリー"] },
    { name: "ウソッキー", gen: 2, types: ["いわ"] },
    { name: "ニョロトノ", gen: 2, types: ["みず"] },
    { name: "ハネッコ", gen: 2, types: ["くさ", "ひこう"] },
    { name: "ポポッコ", gen: 2, types: ["くさ", "ひこう"] },
    { name: "ワタッコ", gen: 2, types: ["くさ", "ひこう"] },
    { name: "エイパム", gen: 2, types: ["ノーマル"] },
    { name: "ヒマナッツ", gen: 2, types: ["くさ"] },
    { name: "キマワリ", gen: 2, types: ["くさ"] },
    { name: "ヤンヤンマ", gen: 2, types: ["むし", "ひこう"] },
    { name: "ウパー", gen: 2, types: ["みず", "じめん"] },
    { name: "ウパー(パルデアのすがた)", gen: 9, types: ["どく", "じめん"] },
    { name: "ヌオー", gen: 2, types: ["みず", "じめん"] },
    { name: "エーフィ", gen: 2, types: ["エスパー"] },
    { name: "ブラッキー", gen: 2, types: ["あく"] },
    { name: "ヤミカラス", gen: 2, types: ["あく", "ひこう"] },
    { name: "ヤドキング", gen: 2, types: ["みず", "エスパー"] },
    { name: "ヤドキング(ガラルのすがた)", gen: 8, types: ["どく", "エスパー"] },
    { name: "ムウマ", gen: 2, types: ["ゴースト"] },
    { name: "アンノーン", gen: 2, types: ["エスパー"] },
    { name: "ソーナンス", gen: 2, types: ["エスパー"] },
    { name: "キリンリキ", gen: 2, types: ["ノーマル", "エスパー"] },
    { name: "クヌギダマ", gen: 2, types: ["むし"] },
    { name: "フォレトス", gen: 2, types: ["むし", "はがね"] },
    { name: "ノコッチ", gen: 2, types: ["ノーマル"] },
    { name: "グライガー", gen: 2, types: ["じめん", "ひこう"] },
    { name: "ハガネール", gen: 2, types: ["はがね", "じめん"] },
    { name: "メガハガネール", gen: "メガシンカ", types: ["はがね", "じめん"] },
    { name: "ブルー", gen: 2, types: ["フェアリー"] },
    { name: "グランブル", gen: 2, types: ["フェアリー"] },
    { name: "ハリーセン", gen: 2, types: ["みず", "どく"] },
    { name: "ハリーセン(ヒスイのすがた)", gen: 8, types: ["あく", "どく"] },
    { name: "ハッサム", gen: 2, types: ["むし", "はがね"] },
    { name: "メガハッサム", gen: "メガシンカ", types: ["むし", "はがね"] },
    { name: "ツボツボ", gen: 2, types: ["むし", "いわ"] },
    { name: "ヘラクロス", gen: 2, types: ["むし", "かくとう"] },
    { name: "メガヘラクロス", gen: "メガシンカ", types: ["むし", "かくとう"] },
    { name: "ニューラ", gen: 2, types: ["あく", "こおり"] },
    { name: "ニューラ(ヒスイのすがた)", gen: 8, types: ["かくとう", "どく"] },
    { name: "ヒメグマ", gen: 2, types: ["ノーマル"] },
    { name: "リングマ", gen: 2, types: ["ノーマル"] },
    { name: "マグマッグ", gen: 2, types: ["ほのお"] },
    { name: "マグカルゴ", gen: 2, types: ["ほのお", "いわ"] },
    { name: "ウリムー", gen: 2, types: ["こおり", "じめん"] },
    { name: "イノムー", gen: 2, types: ["こおり", "じめん"] },
    { name: "サニーゴ", gen: 2, types: ["みず", "いわ"] },
    { name: "サニーゴ(ガラルのすがた)", gen: 8, types: ["ゴースト"] },
    { name: "テッポウオ", gen: 2, types: ["みず"] },
    { name: "オクタン", gen: 2, types: ["みず"] },
    { name: "デリバード", gen: 2, types: ["こおり", "ひこう"] },
    { name: "マンタイン", gen: 2, types: ["みず", "ひこう"] },
    { name: "エアームド", gen: 2, types: ["はがね", "ひこう"] },
    { name: "メガエアームド", gen: "メガシンカ", types: ["はがね", "ひこう"] },
    { name: "デルビル", gen: 2, types: ["あく", "ほのお"] },
    { name: "ヘルガー", gen: 2, types: ["あく", "ほのお"] },
    { name: "メガヘルガー", gen: "メガシンカ", types: ["あく", "ほのお"] },
    { name: "キングドラ", gen: 2, types: ["みず", "ドラゴン"] },
    { name: "ゴマゾウ", gen: 2, types: ["じめん"] },
    { name: "ドンファン", gen: 2, types: ["じめん"] },
    { name: "ポリゴン2", gen: 2, types: ["ノーマル"] },
    { name: "オドシシ", gen: 2, types: ["ノーマル"] },
    { name: "ドーブル", gen: 2, types: ["ノーマル"] },
    { name: "バルキー", gen: 2, types: ["かくとう"] },
    { name: "カポエラー", gen: 2, types: ["かくとう"] },
    { name: "ムチュール", gen: 2, types: ["こおり", "エスパー"] },
    { name: "エレキッド", gen: 2, types: ["でんき"] },
    { name: "ブビィ", gen: 2, types: ["ほのお"] },
    { name: "ミルタンク", gen: 2, types: ["ノーマル"] },
    { name: "ハピナス", gen: 2, types: ["ノーマル"] },
    { name: "ライコウ", gen: 2, types: ["でんき"] },
    { name: "エンテイ", gen: 2, types: ["ほのお"] },
    { name: "スイクン", gen: 2, types: ["みず"] },
    { name: "ヨーギラス", gen: 2, types: ["いわ", "じめん"] },
    { name: "サナギラス", gen: 2, types: ["いわ", "じめん"] },
    { name: "バンギラス", gen: 2, types: ["いわ", "あく"] },
    { name: "メガバンギラス", gen: "メガシンカ", types: ["いわ", "あく"] },
    { name: "ルギア", gen: 2, types: ["エスパー", "ひこう"] },
    { name: "ホウオウ", gen: 2, types: ["ほのお", "ひこう"] },
    { name: "セレビィ", gen: 2, types: ["エスパー", "くさ"] },
    { name: "キモリ", gen: 3, types: ["くさ"] },
    { name: "ジュプトル", gen: 3, types: ["くさ"] },
    { name: "ジュカイン", gen: 3, types: ["くさ"] },
    { name: "メガジュカイン", gen: "メガシンカ", types: ["くさ", "ドラゴン"] },
    { name: "アチャモ", gen: 3, types: ["ほのお"] },
    { name: "ワカシャモ", gen: 3, types: ["ほのお", "かくとう"] },
    { name: "バシャーモ", gen: 3, types: ["ほのお", "かくとう"] },
    { name: "メガバシャーモ", gen: "メガシンカ", types: ["ほのお", "かくとう"] },
    { name: "ミズゴロウ", gen: 3, types: ["みず"] },
    { name: "ヌマクロー", gen: 3, types: ["みず", "じめん"] },
    { name: "ラグラージ", gen: 3, types: ["みず", "じめん"] },
    { name: "メガラグラージ", gen: "メガシンカ", types: ["みず", "じめん"] },
    { name: "ポチエナ", gen: 3, types: ["あく"] },
    { name: "グラエナ", gen: 3, types: ["あく"] },
    { name: "ジグザグマ", gen: 3, types: ["ノーマル"] },
    { name: "ジグザグマ(ガラルのすがた)", gen: 8, types: ["あく", "ノーマル"] },
    { name: "マッスグマ", gen: 3, types: ["ノーマル"] },
    { name: "マッスグマ(ガラルのすがた)", gen: 8, types: ["あく", "ノーマル"] },
    { name: "ケムッソ", gen: 3, types: ["むし"] },
    { name: "カラサリス", gen: 3, types: ["むし"] },
    { name: "アゲハント", gen: 3, types: ["むし", "ひこう"] },
    { name: "マユルド", gen: 3, types: ["むし"] },
    { name: "ドクケイル", gen: 3, types: ["むし", "どく"] },
    { name: "ハスボー", gen: 3, types: ["みず", "くさ"] },
    { name: "ハスブレロ", gen: 3, types: ["みず", "くさ"] },
    { name: "ルンパッパ", gen: 3, types: ["みず", "くさ"] },
    { name: "タネボー", gen: 3, types: ["くさ"] },
    { name: "コノハナ", gen: 3, types: ["くさ", "あく"] },
    { name: "ダーテング", gen: 3, types: ["くさ", "あく"] },
    { name: "スバメ", gen: 3, types: ["ノーマル", "ひこう"] },
    { name: "オオスバメ", gen: 3, types: ["ノーマル", "ひこう"] },
    { name: "キャモメ", gen: 3, types: ["みず", "ひこう"] },
    { name: "ペリッパー", gen: 3, types: ["みず", "ひこう"] },
    { name: "ラルトス", gen: 3, types: ["エスパー", "フェアリー"] },
    { name: "キルリア", gen: 3, types: ["エスパー", "フェアリー"] },
    { name: "サーナイト", gen: 3, types: ["エスパー", "フェアリー"] },
    { name: "メガサーナイト", gen: "メガシンカ", types: ["エスパー", "フェアリー"] },
    { name: "アメタマ", gen: 3, types: ["むし", "みず"] },
    { name: "アメモース", gen: 3, types: ["むし", "ひこう"] },
    { name: "キノココ", gen: 3, types: ["くさ"] },
    { name: "キノガッサ", gen: 3, types: ["くさ", "かくとう"] },
    { name: "ナマケロ", gen: 3, types: ["ノーマル"] },
    { name: "ヤルキモノ", gen: 3, types: ["ノーマル"] },
    { name: "ケッキング", gen: 3, types: ["ノーマル"] },
    { name: "ツチニン", gen: 3, types: ["むし", "じめん"] },
    { name: "テッカニン", gen: 3, types: ["むし", "ひこう"] },
    { name: "ヌケニン", gen: 3, types: ["むし", "ゴースト"] },
    { name: "ゴニョニョ", gen: 3, types: ["ノーマル"] },
    { name: "ドゴーム", gen: 3, types: ["ノーマル"] },
    { name: "バクオング", gen: 3, types: ["ノーマル"] },
    { name: "マクノシタ", gen: 3, types: ["かくとう"] },
    { name: "ハリテヤマ", gen: 3, types: ["かくとう"] },
    { name: "ルリリ", gen: 3, types: ["ノーマル", "フェアリー"] },
    { name: "ノズパス", gen: 3, types: ["いわ"] },
    { name: "エネコ", gen: 3, types: ["ノーマル"] },
    { name: "エネコロロ", gen: 3, types: ["ノーマル"] },
    { name: "ヤミラミ", gen: 3, types: ["あく", "ゴースト"] },
    { name: "メガヤミラミ", gen: "メガシンカ", types: ["あく", "ゴースト"] },
    { name: "クチート", gen: 3, types: ["はがね", "フェアリー"] },
    { name: "メガクチート", gen: "メガシンカ", types: ["はがね", "フェアリー"] },
    { name: "ココドラ", gen: 3, types: ["はがね", "いわ"] },
    { name: "コドラ", gen: 3, types: ["はがね", "いわ"] },
    { name: "ボスゴドラ", gen: 3, types: ["はがね", "いわ"] },
    { name: "メガボスゴドラ", gen: "メガシンカ", types: ["はがね"] },
    { name: "アサナン", gen: 3, types: ["かくとう", "エスパー"] },
    { name: "チャーレム", gen: 3, types: ["かくとう", "エスパー"] },
    { name: "メガチャーレム", gen: "メガシンカ", types: ["かくとう", "エスパー"] },
    { name: "ラクライ", gen: 3, types: ["でんき"] },
    { name: "ライボルト", gen: 3, types: ["でんき"] },
    { name: "メガライボルト", gen: "メガシンカ", types: ["でんき"] },
    { name: "プラスル", gen: 3, types: ["でんき"] },
    { name: "マイナン", gen: 3, types: ["でんき"] },
    { name: "バルビート", gen: 3, types: ["むし"] },
    { name: "イルミーゼ", gen: 3, types: ["むし"] },
    { name: "ロゼリア", gen: 3, types: ["くさ", "どく"] },
    { name: "ゴクリン", gen: 3, types: ["どく"] },
    { name: "マルノーム", gen: 3, types: ["どく"] },
    { name: "キバニア", gen: 3, types: ["みず", "あく"] },
    { name: "サメハダー", gen: 3, types: ["みず", "あく"] },
    { name: "メガサメハダー", gen: "メガシンカ", types: ["みず", "あく"] },
    { name: "ホエルコ", gen: 3, types: ["みず"] },
    { name: "ホエルオー", gen: 3, types: ["みず"] },
    { name: "ドンメル", gen: 3, types: ["ほのお", "じめん"] },
    { name: "バクーダ", gen: 3, types: ["ほのお", "じめん"] },
    { name: "メガバクーダ", gen: "メガシンカ", types: ["ほのお", "じめん"] },
    { name: "コータス", gen: 3, types: ["ほのお"] },
    { name: "バネブー", gen: 3, types: ["エスパー"] },
    { name: "ブーピッグ", gen: 3, types: ["エスパー"] },
    { name: "パッチール", gen: 3, types: ["ノーマル"] },
    { name: "ナックラー", gen: 3, types: ["じめん"] },
    { name: "ビブラーバ", gen: 3, types: ["じめん", "ドラゴン"] },
    { name: "フライゴン", gen: 3, types: ["じめん", "ドラゴン"] },
    { name: "サボネア", gen: 3, types: ["くさ"] },
    { name: "ノクタス", gen: 3, types: ["くさ", "あく"] },
    { name: "チルット", gen: 3, types: ["ノーマル", "ひこう"] },
    { name: "チルタリス", gen: 3, types: ["ドラゴン", "ひこう"] },
    { name: "メガチルタリス", gen: "メガシンカ", types: ["ドラゴン", "フェアリー"] },
    { name: "ザングース", gen: 3, types: ["ノーマル"] },
    { name: "ハブネーク", gen: 3, types: ["どく"] },
    { name: "ルナトーン", gen: 3, types: ["いわ", "エスパー"] },
    { name: "ソルロック", gen: 3, types: ["いわ", "エスパー"] },
    { name: "ドジョッチ", gen: 3, types: ["みず", "じめん"] },
    { name: "ナマズン", gen: 3, types: ["みず", "じめん"] },
    { name: "ヘイガニ", gen: 3, types: ["みず"] },
    { name: "シザリガー", gen: 3, types: ["みず", "あく"] },
    { name: "ヤジロン", gen: 3, types: ["じめん", "エスパー"] },
    { name: "ネンドール", gen: 3, types: ["じめん", "エスパー"] },
    { name: "リリーラ", gen: 3, types: ["いわ", "くさ"] },
    { name: "ユレイドル", gen: 3, types: ["いわ", "くさ"] },
    { name: "アノプス", gen: 3, types: ["いわ", "むし"] },
    { name: "アーマルド", gen: 3, types: ["いわ", "むし"] },
    { name: "ヒンバス", gen: 3, types: ["みず"] },
    { name: "ミロカロス", gen: 3, types: ["みず"] },
    { name: "ポワルン(ポワルンのすがた)", gen: 3, types: ["ノーマル"] },
    { name: "ポワルン(たいようのすがた)", gen: 3, types: ["ほのお"] },
    { name: "ポワルン(あまみずのすがた)", gen: 3, types: ["みず"] },
    { name: "ポワルン(ゆきぐものすがた)", gen: 3, types: ["こおり"] },
    { name: "カクレオン", gen: 3, types: ["ノーマル"] },
    { name: "カゲボウズ", gen: 3, types: ["ゴースト"] },
    { name: "ジュペッタ", gen: 3, types: ["ゴースト"] },
    { name: "メガジュペッタ", gen: "メガシンカ", types: ["ゴースト"] },
    { name: "ヨマワル", gen: 3, types: ["ゴースト"] },
    { name: "サマヨール", gen: 3, types: ["ゴースト"] },
    { name: "トロピウス", gen: 3, types: ["くさ", "ひこう"] },
    { name: "チリーン", gen: 3, types: ["エスパー"] },
    { name: "メガチリーン", gen: "メガシンカ", types: ["エスパー", "はがね"] },
    { name: "アブソル", gen: 3, types: ["あく"] },
    { name: "メガアブソル", gen: "メガシンカ", types: ["あく"] },
    { name: "メガアブソルZ", gen: "メガシンカ", types: ["あく", "ゴースト"] },
    { name: "ソーナノ", gen: 3, types: ["エスパー"] },
    { name: "ユキワラシ", gen: 3, types: ["こおり"] },
    { name: "オニゴーリ", gen: 3, types: ["こおり"] },
    { name: "メガオニゴーリ", gen: "メガシンカ", types: ["こおり"] },
    { name: "タマザラシ", gen: 3, types: ["こおり", "みず"] },
    { name: "トドグラー", gen: 3, types: ["こおり", "みず"] },
    { name: "トドゼルガ", gen: 3, types: ["こおり", "みず"] },
    { name: "パールル", gen: 3, types: ["みず"] },
    { name: "ハンテール", gen: 3, types: ["みず"] },
    { name: "サクラビス", gen: 3, types: ["みず"] },
    { name: "ジーランス", gen: 3, types: ["みず", "いわ"] },
    { name: "ラブカス", gen: 3, types: ["みず"] },
    { name: "タツベイ", gen: 3, types: ["ドラゴン"] },
    { name: "コモルー", gen: 3, types: ["ドラゴン"] },
    { name: "ボーマンダ", gen: 3, types: ["ドラゴン", "ひこう"] },
    { name: "メガボーマンダ", gen: "メガシンカ", types: ["ドラゴン", "ひこう"] },
    { name: "ダンバル", gen: 3, types: ["はがね", "エスパー"] },
    { name: "メタング", gen: 3, types: ["はがね", "エスパー"] },
    { name: "メタグロス", gen: 3, types: ["はがね", "エスパー"] },
    { name: "メガメタグロス", gen: "メガシンカ", types: ["はがね", "エスパー"] },
    { name: "レジロック", gen: 3, types: ["いわ"] },
    { name: "レジアイス", gen: 3, types: ["こおり"] },
    { name: "レジスチル", gen: 3, types: ["はがね"] },
    { name: "ラティアス", gen: 3, types: ["ドラゴン", "エスパー"] },
    { name: "メガラティアス", gen: "メガシンカ", types: ["ドラゴン", "エスパー"] },
    { name: "ラティオス", gen: 3, types: ["ドラゴン", "エスパー"] },
    { name: "メガラティオス", gen: "メガシンカ", types: ["ドラゴン", "エスパー"] },
    { name: "カイオーガ", gen: 3, types: ["みず"] },
    { name: "ゲンシカイオーガ", gen: 3, types: ["みず"] },
    { name: "グラードン", gen: 3, types: ["じめん"] },
    { name: "ゲンシグラードン", gen: 3, types: ["じめん", "ほのお"] },
    { name: "レックウザ", gen: 3, types: ["ドラゴン", "ひこう"] },
    { name: "メガレックウザ", gen: "メガシンカ", types: ["ドラゴン", "ひこう"] },
    { name: "ジラーチ", gen: 3, types: ["はがね", "エスパー"] },
    { name: "デオキシス", gen: 3, types: ["エスパー"] },
    { name: "ナエトル", gen: 4, types: ["くさ"] },
    { name: "ハヤシガメ", gen: 4, types: ["くさ"] },
    { name: "ドダイトス", gen: 4, types: ["くさ", "じめん"] },
    { name: "ヒコザル", gen: 4, types: ["ほのお"] },
    { name: "モウカザル", gen: 4, types: ["ほのお", "かくとう"] },
    { name: "ゴウカザル", gen: 4, types: ["ほのお", "かくとう"] },
    { name: "ポッチャマ", gen: 4, types: ["みず"] },
    { name: "ポッタイシ", gen: 4, types: ["みず"] },
    { name: "エンペルト", gen: 4, types: ["みず", "はがね"] },
    { name: "ムックル", gen: 4, types: ["ノーマル", "ひこう"] },
    { name: "ムクバード", gen: 4, types: ["ノーマル", "ひこう"] },
    { name: "ムクホーク", gen: 4, types: ["ノーマル", "ひこう"] },
    { name: "メガムクホーク", gen: "メガシンカ", types: ["かくとう", "ひこう"] },
    { name: "ビッパ", gen: 4, types: ["ノーマル"] },
    { name: "ビーダル", gen: 4, types: ["ノーマル", "みず"] },
    { name: "コロボーシ", gen: 4, types: ["むし"] },
    { name: "コロトック", gen: 4, types: ["むし"] },
    { name: "コリンク", gen: 4, types: ["でんき"] },
    { name: "ルクシオ", gen: 4, types: ["でんき"] },
    { name: "レントラー", gen: 4, types: ["でんき"] },
    { name: "スボミー", gen: 4, types: ["くさ", "どく"] },
    { name: "ロズレイド", gen: 4, types: ["くさ", "どく"] },
    { name: "ズガイドス", gen: 4, types: ["いわ"] },
    { name: "ラムパルド", gen: 4, types: ["いわ"] },
    { name: "タテトプス", gen: 4, types: ["いわ", "はがね"] },
    { name: "トリデプス", gen: 4, types: ["いわ", "はがね"] },
    { name: "ミノムッチ(くさきのミノ)", gen: 4, types: ["むし"] },
    { name: "ミノムッチ(すなちのミノ)", gen: 4, types: ["むし"] },
    { name: "ミノムッチ(ゴミのミノ)", gen: 4, types: ["むし"] },
    { name: "ミノマダム(くさきのミノ)", gen: 4, types: ["むし", "くさ"] },
    { name: "ミノマダム(すなちのミノ)", gen: 4, types: ["むし", "じめん"] },
    { name: "ミノマダム(ゴミのミノ)", gen: 4, types: ["むし", "はがね"] },
    { name: "ガーメイル", gen: 4, types: ["むし", "ひこう"] },
    { name: "ミツハニー", gen: 4, types: ["むし", "ひこう"] },
    { name: "ビークイン", gen: 4, types: ["むし", "ひこう"] },
    { name: "パチリス", gen: 4, types: ["でんき"] },
    { name: "ブイゼル", gen: 4, types: ["みず"] },
    { name: "フローゼル", gen: 4, types: ["みず"] },
    { name: "チェリンボ", gen: 4, types: ["くさ"] },
    { name: "チェリム(ネガフォルム)", gen: 4, types: ["くさ"] },
    { name: "チェリム(ポジフォルム)", gen: 4, types: ["くさ"] },
    { name: "カラナクシ(にしのうみ)", gen: 4, types: ["みず"] },
    { name: "カラナクシ(ひがしのうみ)", gen: 4, types: ["みず"] },
    { name: "トリトドン(にしのうみ)", gen: 4, types: ["みず", "じめん"] },
    { name: "トリトドン(ひがしのうみ)", gen: 4, types: ["みず", "じめん"] },
    { name: "エテボース", gen: 4, types: ["ノーマル"] },
    { name: "フワンテ", gen: 4, types: ["ゴースト", "ひこう"] },
    { name: "フワライド", gen: 4, types: ["ゴースト", "ひこう"] },
    { name: "ミミロル", gen: 4, types: ["ノーマル"] },
    { name: "ミミロップ", gen: 4, types: ["ノーマル"] },
    { name: "メガミミロップ", gen: "メガシンカ", types: ["ノーマル", "かくとう"] },
    { name: "ムウマージ", gen: 4, types: ["ゴースト"] },
    { name: "ドンカラス", gen: 4, types: ["あく", "ひこう"] },
    { name: "ニャルマー", gen: 4, types: ["ノーマル"] },
    { name: "ブニャット", gen: 4, types: ["ノーマル"] },
    { name: "リーシャン", gen: 4, types: ["エスパー"] },
    { name: "スカンプー", gen: 4, types: ["どく", "あく"] },
    { name: "スカタンク", gen: 4, types: ["どく", "あく"] },
    { name: "ドーミラー", gen: 4, types: ["はがね", "エスパー"] },
    { name: "ドータクン", gen: 4, types: ["はがね", "エスパー"] },
    { name: "ウソハチ", gen: 4, types: ["いわ"] },
    { name: "マネネ", gen: 4, types: ["エスパー", "フェアリー"] },
    { name: "ピンプク", gen: 4, types: ["ノーマル"] },
    { name: "ペラップ", gen: 4, types: ["ノーマル", "ひこう"] },
    { name: "ミカルゲ", gen: 4, types: ["ゴースト", "あく"] },
    { name: "フカマル", gen: 4, types: ["ドラゴン", "じめん"] },
    { name: "ガバイト", gen: 4, types: ["ドラゴン", "じめん"] },
    { name: "ガブリアス", gen: 4, types: ["ドラゴン", "じめん"] },
    { name: "メガガブリアス", gen: "メガシンカ", types: ["ドラゴン", "じめん"] },
    { name: "メガガブリアスZ", gen: "メガシンカ", types: ["ドラゴン"] },
    { name: "ゴンベ", gen: 4, types: ["ノーマル"] },
    { name: "リオル", gen: 4, types: ["かくとう"] },
    { name: "ルカリオ", gen: 4, types: ["かくとう", "はがね"] },
    { name: "メガルカリオ", gen: "メガシンカ", types: ["かくとう", "はがね"] },
    { name: "メガルカリオZ", gen: "メガシンカ", types: ["かくとう", "はがね"] },
    { name: "ヒポポタス", gen: 4, types: ["じめん"] },
    { name: "カバルドン", gen: 4, types: ["じめん"] },
    { name: "スコルピ", gen: 4, types: ["どく", "むし"] },
    { name: "ドラピオン", gen: 4, types: ["どく", "あく"] },
    { name: "グレッグル", gen: 4, types: ["どく", "かくとう"] },
    { name: "ドクロッグ", gen: 4, types: ["どく", "かくとう"] },
    { name: "マスキッパ", gen: 4, types: ["くさ"] },
    { name: "ケイコウオ", gen: 4, types: ["みず"] },
    { name: "ネオラント", gen: 4, types: ["みず"] },
    { name: "タマンタ", gen: 4, types: ["みず", "ひこう"] },
    { name: "ユキカブリ", gen: 4, types: ["くさ", "こおり"] },
    { name: "ユキノオー", gen: 4, types: ["くさ", "こおり"] },
    { name: "メガユキノオー", gen: "メガシンカ", types: ["くさ", "こおり"] },
    { name: "マニューラ", gen: 4, types: ["あく", "こおり"] },
    { name: "ジバコイル", gen: 4, types: ["でんき", "はがね"] },
    { name: "ベロベルト", gen: 4, types: ["ノーマル"] },
    { name: "ドサイドン", gen: 4, types: ["じめん", "いわ"] },
    { name: "モジャンボ", gen: 4, types: ["くさ"] },
    { name: "エレキブル", gen: 4, types: ["でんき"] },
    { name: "ブーバーン", gen: 4, types: ["ほのお"] },
    { name: "トゲキッス", gen: 4, types: ["フェアリー", "ひこう"] },
    { name: "メガヤンマ", gen: "メガシンカ", types: ["むし", "ひこう"] },
    { name: "リーフィア", gen: 4, types: ["くさ"] },
    { name: "グレイシア", gen: 4, types: ["こおり"] },
    { name: "グライオン", gen: 4, types: ["じめん", "ひこう"] },
    { name: "マンムー", gen: 4, types: ["こおり", "じめん"] },
    { name: "ポリゴンZ", gen: 4, types: ["ノーマル"] },
    { name: "エルレイド", gen: 4, types: ["エスパー", "かくとう"] },
    { name: "メガエルレイド", gen: "メガシンカ", types: ["エスパー", "かくとう"] },
    { name: "ダイノーズ", gen: 4, types: ["いわ", "はがね"] },
    { name: "ヨノワール", gen: 4, types: ["ゴースト"] },
    { name: "ユキメノコ", gen: 4, types: ["こおり", "ゴースト"] },
    { name: "メガユキメノコ", gen: "メガシンカ", types: ["こおり", "ゴースト"] },
    { name: "ロトム(ロトムのすがた)", gen: 4, types: ["でんき", "ゴースト"] },
    { name: "ロトム(ヒートロトム)", gen: 4, types: ["でんき", "ほのお"] },
    { name: "ロトム(ウォッシュロトム)", gen: 4, types: ["でんき", "みず"] },
    { name: "ロトム(フロストロトム)", gen: 4, types: ["でんき", "こおり"] },
    { name: "ロトム(スピンロトム)", gen: 4, types: ["でんき", "ひこう"] },
    { name: "ロトム(カットロトム)", gen: 4, types: ["でんき", "くさ"] },
    { name: "ユクシー", gen: 4, types: ["エスパー"] },
    { name: "エムリット", gen: 4, types: ["エスパー"] },
    { name: "アグノム", gen: 4, types: ["エスパー"] },
    { name: "ディアルガ", gen: 4, types: ["はがね", "ドラゴン"] },
    { name: "パルキア", gen: 4, types: ["みず", "ドラゴン"] },
    { name: "ヒードラン", gen: 4, types: ["ほのお", "はがね"] },
    { name: "メガヒードラン", gen: "メガシンカ", types: ["ほのお", "はがね"] },
    { name: "レジギガス", gen: 4, types: ["ノーマル"] },
    { name: "ギラティナ", gen: 4, types: ["ゴースト", "ドラゴン"] },
    { name: "クレセリア", gen: 4, types: ["エスパー"] },
    { name: "フィオネ", gen: 4, types: ["みず"] },
    { name: "マナフィ", gen: 4, types: ["みず"] },
    { name: "ダークライ", gen: 4, types: ["あく"] },
    { name: "メガダークライ", gen: "メガシンカ", types: ["あく"] },
    { name: "シェイミ(ランドフォルム)", gen: 4, types: ["くさ"] },
    { name: "シェイミ(スカイフォルム)", gen: 4, types: ["くさ", "ひこう"] },
    { name: "アルセウス", gen: 4, types: ["ノーマル"] },
    { name: "ビクティニ", gen: 5, types: ["エスパー", "ほのお"] },
    { name: "ツタージャ", gen: 5, types: ["くさ"] },
    { name: "ジャノビー", gen: 5, types: ["くさ"] },
    { name: "ジャローダ", gen: 5, types: ["くさ"] },
    { name: "ポカブ", gen: 5, types: ["ほのお"] },
    { name: "チャオブー", gen: 5, types: ["ほのお", "かくとう"] },
    { name: "エンブオー", gen: 5, types: ["ほのお", "かくとう"] },
    { name: "メガエンブオー", gen: "メガシンカ", types: ["ほのお", "かくとう"] },
    { name: "ミジュマル", gen: 5, types: ["みず"] },
    { name: "フタチマル", gen: 5, types: ["みず"] },
    { name: "ダイケンキ", gen: 5, types: ["みず"] },
    { name: "ダイケンキ(ヒスイのすがた)", gen: 8, types: ["みず", "あく"] },
    { name: "ミネズミ", gen: 5, types: ["ノーマル"] },
    { name: "ミルホッグ", gen: 5, types: ["ノーマル"] },
    { name: "ヨーテリー", gen: 5, types: ["ノーマル"] },
    { name: "ハーデリア", gen: 5, types: ["ノーマル"] },
    { name: "ムーランド", gen: 5, types: ["ノーマル"] },
    { name: "チョロネコ", gen: 5, types: ["あく"] },
    { name: "レパルダス", gen: 5, types: ["あく"] },
    { name: "ヤナップ", gen: 5, types: ["くさ"] },
    { name: "ヤナッキー", gen: 5, types: ["くさ"] },
    { name: "バオップ", gen: 5, types: ["ほのお"] },
    { name: "バオッキー", gen: 5, types: ["ほのお"] },
    { name: "ヒヤップ", gen: 5, types: ["みず"] },
    { name: "ヒヤッキー", gen: 5, types: ["みず"] },
    { name: "ムンナ", gen: 5, types: ["エスパー"] },
    { name: "ムシャーナ", gen: 5, types: ["エスパー"] },
    { name: "マメパト", gen: 5, types: ["ノーマル", "ひこう"] },
    { name: "ハトーボー", gen: 5, types: ["ノーマル", "ひこう"] },
    { name: "ケンホロウ(オスのすがた)", gen: 5, types: ["ノーマル", "ひこう"] },
    { name: "ケンホロウ(メスのすがた)", gen: 5, types: ["ノーマル", "ひこう"] },
    { name: "シママ", gen: 5, types: ["でんき"] },
    { name: "ゼブライカ", gen: 5, types: ["でんき"] },
    { name: "ダンゴロ", gen: 5, types: ["いわ"] },
    { name: "ガントル", gen: 5, types: ["いわ"] },
    { name: "ギガイアス", gen: 5, types: ["いわ"] },
    { name: "コロモリ", gen: 5, types: ["エスパー", "ひこう"] },
    { name: "ココロモリ", gen: 5, types: ["エスパー", "ひこう"] },
    { name: "モグリュー", gen: 5, types: ["じめん"] },
    { name: "ドリュウズ", gen: 5, types: ["じめん", "はがね"] },
    { name: "メガドリュウズ", gen: "メガシンカ", types: ["じめん", "はがね"] },
    { name: "タブンネ", gen: 5, types: ["ノーマル"] },
    { name: "メガタブンネ", gen: "メガシンカ", types: ["ノーマル", "フェアリー"] },
    { name: "ドッコラー", gen: 5, types: ["かくとう"] },
    { name: "ドテッコツ", gen: 5, types: ["かくとう"] },
    { name: "ローブシン", gen: 5, types: ["かくとう"] },
    { name: "オタマロ", gen: 5, types: ["みず"] },
    { name: "ガマガル", gen: 5, types: ["みず", "じめん"] },
    { name: "ガマゲロゲ", gen: 5, types: ["みず", "じめん"] },
    { name: "ナゲキ", gen: 5, types: ["かくとう"] },
    { name: "ダゲキ", gen: 5, types: ["かくとう"] },
    { name: "クルミル", gen: 5, types: ["むし", "くさ"] },
    { name: "クルマユ", gen: 5, types: ["むし", "くさ"] },
    { name: "ハハコモリ", gen: 5, types: ["むし", "くさ"] },
    { name: "フシデ", gen: 5, types: ["むし", "どく"] },
    { name: "ホイーガ", gen: 5, types: ["むし", "どく"] },
    { name: "ペンドラー", gen: 5, types: ["むし", "どく"] },
    { name: "メガペンドラー", gen: "メガシンカ", types: ["むし", "どく"] },
    { name: "モンメン", gen: 5, types: ["くさ", "フェアリー"] },
    { name: "エルフーン", gen: 5, types: ["くさ", "フェアリー"] },
    { name: "チュリネ", gen: 5, types: ["くさ"] },
    { name: "ドレディア", gen: 5, types: ["くさ"] },
    { name: "ドレディア(ヒスイのすがた)", gen: 8, types: ["くさ", "かくとう"] },
    { name: "バスラオ(あかすじのすがた)", gen: 5, types: ["みず"] },
    { name: "バスラオ(あおすじのすがた)", gen: 5, types: ["みず"] },
    { name: "バスラオ(しろすじのすがた)", gen: 8, types: ["みず"] },
    { name: "メグロコ", gen: 5, types: ["じめん", "あく"] },
    { name: "ワルビル", gen: 5, types: ["じめん", "あく"] },
    { name: "ワルビアル", gen: 5, types: ["じめん", "あく"] },
    { name: "ダルマッカ", gen: 5, types: ["ほのお"] },
    { name: "ダルマッカ(ガラルのすがた)", gen: 8, types: ["こおり"] },
    { name: "ヒヒダルマ", gen: 5, types: ["ほのお"] },
    { name: "ヒヒダルマ(ダルマモード)", gen: 5, types: ["ほのお", "エスパー"] },
    { name: "ヒヒダルマ(ガラルのすがた)", gen: 8, types: ["こおり"] },
    { name: "ヒヒダルマ(ガラルのすがた・ダルマモード)", gen: 8, types: ["こおり", "ほのお"] },
    { name: "マラカッチ", gen: 5, types: ["くさ"] },
    { name: "イシズマイ", gen: 5, types: ["むし", "いわ"] },
    { name: "イワパレス", gen: 5, types: ["むし", "いわ"] },
    { name: "ズルッグ", gen: 5, types: ["あく", "かくとう"] },
    { name: "ズルズキン", gen: 5, types: ["あく", "かくとう"] },
    { name: "メガズルズキン", gen: "メガシンカ", types: ["あく", "かくとう"] },
    { name: "シンボラー", gen: 5, types: ["エスパー", "ひこう"] },
    { name: "デスマス", gen: 5, types: ["ゴースト"] },
    { name: "デスマス(ガラルのすがた)", gen: 8, types: ["じめん", "ゴースト"] },
    { name: "デスカーン", gen: 5, types: ["ゴースト"] },
    { name: "プロトーガ", gen: 5, types: ["みず", "いわ"] },
    { name: "アバゴーラ", gen: 5, types: ["みず", "いわ"] },
    { name: "アーケン", gen: 5, types: ["いわ", "ひこう"] },
    { name: "アーケオス", gen: 5, types: ["いわ", "ひこう"] },
    { name: "ヤブクロン", gen: 5, types: ["どく"] },
    { name: "ダストダス", gen: 5, types: ["どく"] },
    { name: "ダストダス(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["どく"] },
    { name: "ゾロア", gen: 5, types: ["あく"] },
    { name: "ゾロア(ヒスイのすがた)", gen: 8, types: ["ノーマル", "ゴースト"] },
    { name: "ゾロアーク", gen: 5, types: ["あく"] },
    { name: "ゾロアーク(ヒスイのすがた)", gen: 8, types: ["ノーマル", "ゴースト"] },
    { name: "チラーミィ", gen: 5, types: ["ノーマル"] },
    { name: "チラチーノ", gen: 5, types: ["ノーマル"] },
    { name: "ゴチム", gen: 5, types: ["エスパー"] },
    { name: "ゴチミル", gen: 5, types: ["エスパー"] },
    { name: "ゴチルゼル", gen: 5, types: ["エスパー"] },
    { name: "ユニラン", gen: 5, types: ["エスパー"] },
    { name: "ダブラン", gen: 5, types: ["エスパー"] },
    { name: "ランクルス", gen: 5, types: ["エスパー"] },
    { name: "コアルヒー", gen: 5, types: ["みず", "ひこう"] },
    { name: "スワンナ", gen: 5, types: ["みず", "ひこう"] },
    { name: "バニプッチ", gen: 5, types: ["こおり"] },
    { name: "バニリッチ", gen: 5, types: ["こおり"] },
    { name: "バイバニラ", gen: 5, types: ["こおり"] },
    { name: "シキジカ(はるのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "シキジカ(なつのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "シキジカ(あきのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "シキジカ(ふゆのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "メブキジカ(はるのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "メブキジカ(なつのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "メブキジカ(あきのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "メブキジカ(ふゆのすがた)", gen: 5, types: ["ノーマル", "くさ"] },
    { name: "エモンガ", gen: 5, types: ["でんき", "ひこう"] },
    { name: "カブルモ", gen: 5, types: ["むし"] },
    { name: "シュバルゴ", gen: 5, types: ["むし", "はがね"] },
    { name: "タマゲタケ", gen: 5, types: ["くさ", "どく"] },
    { name: "モロバレル", gen: 5, types: ["くさ", "どく"] },
    { name: "プルリル(オスのすがた)", gen: 5, types: ["みず", "ゴースト"] },
    { name: "プルリル(メスのすがた)", gen: 5, types: ["みず", "ゴースト"] },
    { name: "ブルンゲル(オスのすがた)", gen: 5, types: ["みず", "ゴースト"] },
    { name: "ブルンゲル(メスのすがた)", gen: 5, types: ["みず", "ゴースト"] },
    { name: "ママンボウ", gen: 5, types: ["みず"] },
    { name: "バチュル", gen: 5, types: ["むし", "でんき"] },
    { name: "デンチュラ", gen: 5, types: ["むし", "でんき"] },
    { name: "テッシード", gen: 5, types: ["くさ", "はがね"] },
    { name: "ナットレイ", gen: 5, types: ["くさ", "はがね"] },
    { name: "ギアル", gen: 5, types: ["はがね"] },
    { name: "ギギアル", gen: 5, types: ["はがね"] },
    { name: "ギギギアル", gen: 5, types: ["はがね"] },
    { name: "シビシラス", gen: 5, types: ["でんき"] },
    { name: "シビビール", gen: 5, types: ["でんき"] },
    { name: "シビルドン", gen: 5, types: ["でんき"] },
    { name: "メガシビルドン", gen: "メガシンカ", types: ["でんき"] },
    { name: "リグレー", gen: 5, types: ["エスパー"] },
    { name: "オーベム", gen: 5, types: ["エスパー"] },
    { name: "ヒトモシ", gen: 5, types: ["ゴースト", "ほのお"] },
    { name: "ランプラー", gen: 5, types: ["ゴースト", "ほのお"] },
    { name: "シャンデラ", gen: 5, types: ["ゴースト", "ほのお"] },
    { name: "メガシャンデラ", gen: "メガシンカ", types: ["ゴースト", "ほのお"] },
    { name: "キバゴ", gen: 5, types: ["ドラゴン"] },
    { name: "オノンド", gen: 5, types: ["ドラゴン"] },
    { name: "オノノクス", gen: 5, types: ["ドラゴン"] },
    { name: "クマシュン", gen: 5, types: ["こおり"] },
    { name: "ツンベアー", gen: 5, types: ["こおり"] },
    { name: "フリージオ", gen: 5, types: ["こおり"] },
    { name: "チョボマキ", gen: 5, types: ["むし"] },
    { name: "アギルダー", gen: 5, types: ["むし"] },
    { name: "マッギョ", gen: 5, types: ["じめん", "でんき"] },
    { name: "マッギョ(ガラルのすがた)", gen: 8, types: ["じめん", "はがね"] },
    { name: "コジョフー", gen: 5, types: ["かくとう"] },
    { name: "コジョンド", gen: 5, types: ["かくとう"] },
    { name: "クリムガン", gen: 5, types: ["ドラゴン"] },
    { name: "ゴビット", gen: 5, types: ["じめん", "ゴースト"] },
    { name: "ゴルーグ", gen: 5, types: ["じめん", "ゴースト"] },
    { name: "メガゴルーグ", gen: "メガシンカ", types: ["じめん", "ゴースト"] },
    { name: "コマタナ", gen: 5, types: ["あく", "はがね"] },
    { name: "キリキザン", gen: 5, types: ["あく", "はがね"] },
    { name: "バッフロン", gen: 5, types: ["ノーマル"] },
    { name: "ワシボン", gen: 5, types: ["ノーマル", "ひこう"] },
    { name: "ウォーグル", gen: 5, types: ["ノーマル", "ひこう"] },
    { name: "ウォーグル(ヒスイのすがた)", gen: 8, types: ["エスパー", "ひこう"] },
    { name: "バルチャイ", gen: 5, types: ["あく", "ひこう"] },
    { name: "バルジーナ", gen: 5, types: ["あく", "ひこう"] },
    { name: "クイタラン", gen: 5, types: ["ほのお"] },
    { name: "アイアント", gen: 5, types: ["むし", "はがね"] },
    { name: "モノズ", gen: 5, types: ["あく", "ドラゴン"] },
    { name: "ジヘッド", gen: 5, types: ["あく", "ドラゴン"] },
    { name: "サザンドラ", gen: 5, types: ["あく", "ドラゴン"] },
    { name: "メラルバ", gen: 5, types: ["むし", "ほのお"] },
    { name: "ウルガモス", gen: 5, types: ["むし", "ほのお"] },
    { name: "コバルオン", gen: 5, types: ["はがね", "かくとう"] },
    { name: "テラキオン", gen: 5, types: ["いわ", "かくとう"] },
    { name: "ビリジオン", gen: 5, types: ["くさ", "かくとう"] },
    { name: "トルネロス(けしんフォルム)", gen: 5, types: ["ひこう"] },
    { name: "トルネロス(れいじゅうフォルム)", gen: 5, types: ["ひこう"] },
    { name: "ボルトロス(けしんフォルム)", gen: 5, types: ["でんき", "ひこう"] },
    { name: "ボルトロス(れいじゅうフォルム)", gen: 5, types: ["でんき", "ひこう"] },
    { name: "レシラム", gen: 5, types: ["ドラゴン", "ほのお"] },
    { name: "ゼクロム", gen: 5, types: ["ドラゴン", "でんき"] },
    { name: "ランドロス(けしんフォルム)", gen: 5, types: ["じめん", "ひこう"] },
    { name: "ランドロス(れいじゅうフォルム)", gen: 5, types: ["じめん", "ひこう"] },
    { name: "キュレム(キュレムのすがた)", gen: 5, types: ["ドラゴン", "こおり"] },
    { name: "キュレム(ホワイトキュレム)", gen: 5, types: ["ドラゴン", "こおり"] },
    { name: "キュレム(ブラックキュレム)", gen: 5, types: ["ドラゴン", "こおり"] },
    { name: "ケルディオ(いつものすがた)", gen: 5, types: ["みず", "かくとう"] },
    { name: "ケルディオ(かくごのすがた)", gen: 5, types: ["みず", "かくとう"] },
    { name: "メロエッタ(ボイスフォルム)", gen: 5, types: ["ノーマル", "エスパー"] },
    { name: "メロエッタ(ステップフォルム)", gen: 5, types: ["ノーマル", "かくとう"] },
    { name: "ゲノセクト", gen: 5, types: ["むし", "はがね"] },
    { name: "ハリマロン", gen: 6, types: ["くさ"] },
    { name: "ハリボーグ", gen: 6, types: ["くさ"] },
    { name: "ブリガロン", gen: 6, types: ["くさ", "かくとう"] },
    { name: "メガブリガロン", gen: "メガシンカ", types: ["くさ", "かくとう"] },
    { name: "フォッコ", gen: 6, types: ["ほのお"] },
    { name: "テールナー", gen: 6, types: ["ほのお"] },
    { name: "マフォクシー", gen: 6, types: ["ほのお", "エスパー"] },
    { name: "メガマフォクシー", gen: "メガシンカ", types: ["ほのお", "エスパー"] },
    { name: "ケロマツ", gen: 6, types: ["みず"] },
    { name: "ゲコガシラ", gen: 6, types: ["みず"] },
    { name: "ゲッコウガ", gen: 6, types: ["みず", "あく"] },
    { name: "メガゲッコウガ", gen: "メガシンカ", types: ["みず", "あく"] },
    { name: "ホルビー", gen: 6, types: ["ノーマル"] },
    { name: "ホルード", gen: 6, types: ["ノーマル", "じめん"] },
    { name: "ヤヤコマ", gen: 6, types: ["ノーマル", "ひこう"] },
    { name: "ヒノヤコマ", gen: 6, types: ["ほのお", "ひこう"] },
    { name: "ファイアロー", gen: 6, types: ["ほのお", "ひこう"] },
    { name: "コフキムシ", gen: 6, types: ["むし"] },
    { name: "コフーライ", gen: 6, types: ["むし"] },
    { name: "ビビヨン", gen: 6, types: ["むし", "ひこう"] },
    { name: "シシコ", gen: 6, types: ["ほのお", "ノーマル"] },
    { name: "カエンジシ(オスのすがた)", gen: 6, types: ["ほのお", "ノーマル"] },
    { name: "カエンジシ(メスのすがた)", gen: 6, types: ["ほのお", "ノーマル"] },
    { name: "メガカエンジシ", gen: "メガシンカ", types: ["ほのお", "ノーマル"] },
    { name: "フラベベ", gen: 6, types: ["フェアリー"] },
    { name: "フラエッテ", gen: 6, types: ["フェアリー"] },
    { name: "フラエッテ(えいえんのはな)", gen: 6, types: ["フェアリー"] },
    { name: "メガフラエッテ", gen: "メガシンカ", types: ["フェアリー"] },
    { name: "フラージェス", gen: 6, types: ["フェアリー"] },
    { name: "メェークル", gen: 6, types: ["くさ"] },
    { name: "ゴーゴート", gen: 6, types: ["くさ"] },
    { name: "ヤンチャム", gen: 6, types: ["かくとう"] },
    { name: "ゴロンダ", gen: 6, types: ["かくとう", "あく"] },
    { name: "トリミアン", gen: 6, types: ["ノーマル"] },
    { name: "ニャスパー", gen: 6, types: ["エスパー"] },
    { name: "ニャオニクス(オスのすがた)", gen: 6, types: ["エスパー"] },
    { name: "ニャオニクス(メスのすがた)", gen: 6, types: ["エスパー"] },
    { name: "メガニャオニクス", gen: "メガシンカ", types: ["エスパー"] },
    { name: "ヒトツキ", gen: 6, types: ["はがね", "ゴースト"] },
    { name: "ニダンギル", gen: 6, types: ["はがね", "ゴースト"] },
    { name: "ギルガルド(シールドフォルム)", gen: 6, types: ["はがね", "ゴースト"] },
    { name: "ギルガルド(ブレードフォルム)", gen: 6, types: ["はがね", "ゴースト"] },
    { name: "シュシュプ", gen: 6, types: ["フェアリー"] },
    { name: "フレフワン", gen: 6, types: ["フェアリー"] },
    { name: "ペロッパフ", gen: 6, types: ["フェアリー"] },
    { name: "ペロリーム", gen: 6, types: ["フェアリー"] },
    { name: "マーイーカ", gen: 6, types: ["あく", "エスパー"] },
    { name: "カラマネロ", gen: 6, types: ["あく", "エスパー"] },
    { name: "メガカラマネロ", gen: "メガシンカ", types: ["あく", "エスパー"] },
    { name: "カメテテ", gen: 6, types: ["いわ", "みず"] },
    { name: "ガメノデス", gen: 6, types: ["いわ", "みず"] },
    { name: "メガガメノデス", gen: "メガシンカ", types: ["いわ", "かくとう"] },
    { name: "クズモー", gen: 6, types: ["どく", "みず"] },
    { name: "ドラミドロ", gen: 6, types: ["どく", "ドラゴン"] },
    { name: "メガドラミドロ", gen: "メガシンカ", types: ["どく", "ドラゴン"] },
    { name: "ウデッポウ", gen: 6, types: ["みず"] },
    { name: "ブロスター", gen: 6, types: ["みず"] },
    { name: "エリキテル", gen: 6, types: ["でんき", "ノーマル"] },
    { name: "エレザード", gen: 6, types: ["でんき", "ノーマル"] },
    { name: "チゴラス", gen: 6, types: ["いわ", "ドラゴン"] },
    { name: "ガチゴラス", gen: 6, types: ["いわ", "ドラゴン"] },
    { name: "アマルス", gen: 6, types: ["いわ", "こおり"] },
    { name: "アマルルガ", gen: 6, types: ["いわ", "こおり"] },
    { name: "ニンフィア", gen: 6, types: ["フェアリー"] },
    { name: "ルチャブル", gen: 6, types: ["かくとう", "ひこう"] },
    { name: "メガルチャブル", gen: "メガシンカ", types: ["かくとう", "ひこう"] },
    { name: "デデンネ", gen: 6, types: ["でんき", "フェアリー"] },
    { name: "メレシー", gen: 6, types: ["いわ", "フェアリー"] },
    { name: "ヌメラ", gen: 6, types: ["ドラゴン"] },
    { name: "ヌメイル", gen: 6, types: ["ドラゴン"] },
    { name: "ヌメイル(ヒスイのすがた)", gen: 8, types: ["はがね", "ドラゴン"] },
    { name: "ヌメルゴン", gen: 6, types: ["ドラゴン"] },
    { name: "ヌメルゴン(ヒスイのすがた)", gen: 8, types: ["はがね", "ドラゴン"] },
    { name: "クレッフィ", gen: 6, types: ["はがね", "フェアリー"] },
    { name: "ボクレー", gen: 6, types: ["ゴースト", "くさ"] },
    { name: "オーロット", gen: 6, types: ["ゴースト", "くさ"] },
    { name: "バケッチャ", gen: 6, types: ["ゴースト", "くさ"] },
    { name: "パンプジン", gen: 6, types: ["ゴースト", "くさ"] },
    { name: "カチコール", gen: 6, types: ["こおり"] },
    { name: "クレベース", gen: 6, types: ["こおり"] },
    { name: "クレベース(ヒスイのすがた)", gen: 8, types: ["こおり", "いわ"] },
    { name: "オンバット", gen: 6, types: ["ひこう", "ドラゴン"] },
    { name: "オンバーン", gen: 6, types: ["ひこう", "ドラゴン"] },
    { name: "ゼルネアス", gen: 6, types: ["フェアリー"] },
    { name: "イベルタル", gen: 6, types: ["あく", "ひこう"] },
    { name: "ジガルデ(50%フォルム)", gen: 6, types: ["ドラゴン", "じめん"] },
    { name: "ジガルデ(10%フォルム)", gen: 6, types: ["ドラゴン", "じめん"] },
    { name: "ジガルデ(パーフェクトフォルム)", gen: 6, types: ["ドラゴン", "じめん"] },
    { name: "メガジガルデ", gen: "メガシンカ", types: ["ドラゴン", "じめん"] },
    { name: "ディアンシー", gen: 6, types: ["いわ", "フェアリー"] },
    { name: "メガディアンシー", gen: "メガシンカ", types: ["いわ", "フェアリー"] },
    { name: "フーパ(いましめられしフーパ)", gen: 6, types: ["エスパー", "ゴースト"] },
    { name: "フーパ(ときはなたれしフーパ)", gen: 6, types: ["エスパー", "あく"] },
    { name: "ボルケニオン", gen: 6, types: ["ほのお", "みず"] },
    { name: "モクロー", gen: 7, types: ["くさ", "ひこう"] },
    { name: "フクスロー", gen: 7, types: ["くさ", "ひこう"] },
    { name: "ジュナイパー", gen: 7, types: ["くさ", "ゴースト"] },
    { name: "ジュナイパー(ヒスイのすがた)", gen: 8, types: ["くさ", "かくとう"] },
    { name: "ニャビー", gen: 7, types: ["ほのお"] },
    { name: "ニャヒート", gen: 7, types: ["ほのお"] },
    { name: "ガオガエン", gen: 7, types: ["ほのお", "あく"] },
    { name: "アシマリ", gen: 7, types: ["みず"] },
    { name: "オシャマリ", gen: 7, types: ["みず"] },
    { name: "アシレーヌ", gen: 7, types: ["みず", "フェアリー"] },
    { name: "ツツケラ", gen: 7, types: ["ノーマル", "ひこう"] },
    { name: "ケララッパ", gen: 7, types: ["ノーマル", "ひこう"] },
    { name: "ドデカバシ", gen: 7, types: ["ノーマル", "ひこう"] },
    { name: "ヤングース", gen: 7, types: ["ノーマル"] },
    { name: "デカグース", gen: 7, types: ["ノーマル"] },
    { name: "アゴジムシ", gen: 7, types: ["むし"] },
    { name: "デンヂムシ", gen: 7, types: ["むし", "でんき"] },
    { name: "クワガノン", gen: 7, types: ["むし", "でんき"] },
    { name: "マケンカニ", gen: 7, types: ["かくとう"] },
    { name: "ケケンカニ", gen: 7, types: ["かくとう", "こおり"] },
    { name: "メガケケンカニ", gen: "メガシンカ", types: ["かくとう", "こおり"] },
    { name: "オドリドリ(めらめらスタイル)", gen: 7, types: ["ほのお", "ひこう"] },
    { name: "オドリドリ(ぱちぱちスタイル)", gen: 7, types: ["でんき", "ひこう"] },
    { name: "オドリドリ(ふらふらスタイル)", gen: 7, types: ["エスパー", "ひこう"] },
    { name: "オドリドリ(まいまいスタイル)", gen: 7, types: ["ゴースト", "ひこう"] },
    { name: "アブリー", gen: 7, types: ["むし", "フェアリー"] },
    { name: "アブリボン", gen: 7, types: ["むし", "フェアリー"] },
    { name: "イワンコ", gen: 7, types: ["いわ"] },
    { name: "ルガルガン(まひるのすがた)", gen: 7, types: ["いわ"] },
    { name: "ルガルガン(まよるのすがた)", gen: 7, types: ["いわ"] },
    { name: "ルガルガン(たそがれのすがた)", gen: 7, types: ["いわ"] },
    { name: "ヨワシ(たんどくのすがた)", gen: 7, types: ["みず"] },
    { name: "ヨワシ(むれたすがた)", gen: 7, types: ["みず"] },
    { name: "ヒドイデ", gen: 7, types: ["どく", "みず"] },
    { name: "ドヒドイデ", gen: 7, types: ["どく", "みず"] },
    { name: "ドロバンコ", gen: 7, types: ["じめん"] },
    { name: "バンバドロ", gen: 7, types: ["じめん"] },
    { name: "シズクモ", gen: 7, types: ["みず", "むし"] },
    { name: "オニシズクモ", gen: 7, types: ["みず", "むし"] },
    { name: "カリキリ", gen: 7, types: ["くさ"] },
    { name: "ラランテス", gen: 7, types: ["くさ"] },
    { name: "ネマシュ", gen: 7, types: ["くさ", "フェアリー"] },
    { name: "マシェード", gen: 7, types: ["くさ", "フェアリー"] },
    { name: "ヤトウモリ", gen: 7, types: ["どく", "ほのお"] },
    { name: "エンニュート", gen: 7, types: ["どく", "ほのお"] },
    { name: "ヌイコグマ", gen: 7, types: ["ノーマル", "かくとう"] },
    { name: "キテルグマ", gen: 7, types: ["ノーマル", "かくとう"] },
    { name: "アマカジ", gen: 7, types: ["くさ"] },
    { name: "アママイコ", gen: 7, types: ["くさ"] },
    { name: "アマージョ", gen: 7, types: ["くさ"] },
    { name: "キュワワー", gen: 7, types: ["フェアリー"] },
    { name: "ヤレユータン", gen: 7, types: ["ノーマル", "エスパー"] },
    { name: "ナゲツケサル", gen: 7, types: ["かくとう"] },
    { name: "コソクムシ", gen: 7, types: ["むし", "みず"] },
    { name: "グソクムシャ", gen: 7, types: ["むし", "みず"] },
    { name: "メガグソクムシャ", gen: "メガシンカ", types: ["むし", "はがね"] },
    { name: "スナバァ", gen: 7, types: ["ゴースト", "じめん"] },
    { name: "シロデスナ", gen: 7, types: ["ゴースト", "じめん"] },
    { name: "ナマコブシ", gen: 7, types: ["みず"] },
    { name: "タイプ:ヌル", gen: 7, types: ["ノーマル"] },
    { name: "シルヴァディ", gen: 7, types: ["ノーマル"] },
    { name: "メテノ(りゅうせいのすがた)", gen: 7, types: ["いわ", "ひこう"] },
    { name: "メテノ(コア)", gen: 7, types: ["いわ", "ひこう"] },
    { name: "ネッコアラ", gen: 7, types: ["ノーマル"] },
    { name: "バクガメス", gen: 7, types: ["ほのお", "ドラゴン"] },
    { name: "トゲデマル", gen: 7, types: ["でんき", "はがね"] },
    { name: "ミミッキュ", gen: 7, types: ["ゴースト", "フェアリー"] },
    { name: "ハギギシリ", gen: 7, types: ["みず", "エスパー"] },
    { name: "ジジーロン", gen: 7, types: ["ノーマル", "ドラゴン"] },
    { name: "メガジジーロン", gen: "メガシンカ", types: ["ノーマル", "ドラゴン"] },
    { name: "ダダリン", gen: 7, types: ["ゴースト", "くさ"] },
    { name: "ジャラコ", gen: 7, types: ["ドラゴン"] },
    { name: "ジャランゴ", gen: 7, types: ["ドラゴン", "かくとう"] },
    { name: "ジャラランガ", gen: 7, types: ["ドラゴン", "かくとう"] },
    { name: "カプ・コケコ", gen: 7, types: ["でんき", "フェアリー"] },
    { name: "カプ・テテフ", gen: 7, types: ["エスパー", "フェアリー"] },
    { name: "カプ・ブルル", gen: 7, types: ["くさ", "フェアリー"] },
    { name: "カプ・レヒレ", gen: 7, types: ["みず", "フェアリー"] },
    { name: "コスモッグ", gen: 7, types: ["エスパー"] },
    { name: "コスモウム", gen: 7, types: ["エスパー"] },
    { name: "ソルガレオ", gen: 7, types: ["エスパー", "はがね"] },
    { name: "ルナアーラ", gen: 7, types: ["エスパー", "ゴースト"] },
    { name: "ウツロイド", gen: 7, types: ["いわ", "どく"] },
    { name: "マッシブーン", gen: 7, types: ["むし", "かくとう"] },
    { name: "フェローチェ", gen: 7, types: ["むし", "かくとう"] },
    { name: "デンジュモク", gen: 7, types: ["でんき"] },
    { name: "テッカグヤ", gen: 7, types: ["はがね", "ひこう"] },
    { name: "カミツルギ", gen: 7, types: ["くさ", "はがね"] },
    { name: "アクジキング", gen: 7, types: ["あく", "ドラゴン"] },
    { name: "ネクロズマ", gen: 7, types: ["エスパー"] },
    { name: "ネクロズマ(たそがれのたてがみ)", gen: 7, types: ["エスパー", "はがね"] },
    { name: "ネクロズマ(あかつきのつばさ)", gen: 7, types: ["エスパー", "ゴースト"] },
    { name: "ネクロズマ(ウルトラネクロズマ)", gen: 7, types: ["エスパー", "ドラゴン"] },
    { name: "マギアナ", gen: 7, types: ["はがね", "フェアリー"] },
    { name: "マギアナ(500ねんまえのいろ)", gen: 7, types: ["はがね", "フェアリー"] },
    { name: "メガマギアナ", gen: "メガシンカ", types: ["はがね", "フェアリー"] },
    { name: "メガマギアナ(500ねんまえのいろ)", gen: "メガシンカ", types: ["はがね", "フェアリー"] },
    { name: "マーシャドー", gen: 7, types: ["かくとう", "ゴースト"] },
    { name: "ベベノム", gen: 7, types: ["どく"] },
    { name: "アーゴヨン", gen: 7, types: ["どく", "ドラゴン"] },
    { name: "ツンデツンデ", gen: 7, types: ["いわ", "はがね"] },
    { name: "ズガドーン", gen: 7, types: ["ほのお", "ゴースト"] },
    { name: "ゼラオラ", gen: 7, types: ["でんき"] },
    { name: "メガゼラオラ", gen: "メガシンカ", types: ["でんき"] },
    { name: "メルタン", gen: 7, types: ["はがね"] },
    { name: "メルメタル", gen: 7, types: ["はがね"] },
    { name: "メルメタル(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["はがね"] },
    { name: "サルノリ", gen: 8, types: ["くさ"] },
    { name: "バチンキー", gen: 8, types: ["くさ"] },
    { name: "ゴリランダー", gen: 8, types: ["くさ"] },
    { name: "ゴリランダー(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["くさ"] },
    { name: "ヒバニー", gen: 8, types: ["ほのお"] },
    { name: "ラビフット", gen: 8, types: ["ほのお"] },
    { name: "エースバーン", gen: 8, types: ["ほのお"] },
    { name: "エースバーン(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ほのお"] },
    { name: "メッソン", gen: 8, types: ["みず"] },
    { name: "ジメレオン", gen: 8, types: ["みず"] },
    { name: "インテレオン", gen: 8, types: ["みず"] },
    { name: "インテレオン(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["みず"] },
    { name: "ホシガリス", gen: 8, types: ["ノーマル"] },
    { name: "ヨクバリス", gen: 8, types: ["ノーマル"] },
    { name: "ココガラ", gen: 8, types: ["ひこう"] },
    { name: "アオガラス", gen: 8, types: ["ひこう"] },
    { name: "アーマーガア", gen: 8, types: ["ひこう", "はがね"] },
    { name: "アーマーガア(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ひこう", "はがね"] },
    { name: "サッチムシ", gen: 8, types: ["むし"] },
    { name: "レドームシ", gen: 8, types: ["むし", "エスパー"] },
    { name: "イオルブ", gen: 8, types: ["むし", "エスパー"] },
    { name: "イオルブ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["むし", "エスパー"] },
    { name: "クスネ", gen: 8, types: ["あく"] },
    { name: "フォクスライ", gen: 8, types: ["あく"] },
    { name: "ヒメンカ", gen: 8, types: ["くさ"] },
    { name: "ワタシラガ", gen: 8, types: ["くさ"] },
    { name: "ウールー", gen: 8, types: ["ノーマル"] },
    { name: "バイウールー", gen: 8, types: ["ノーマル"] },
    { name: "カムカメ", gen: 8, types: ["みず"] },
    { name: "カジリガメ", gen: 8, types: ["みず", "いわ"] },
    { name: "カジリガメ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["みず", "いわ"] },
    { name: "ワンパチ", gen: 8, types: ["でんき"] },
    { name: "パルスワン", gen: 8, types: ["でんき"] },
    { name: "タンドン", gen: 8, types: ["いわ"] },
    { name: "トロッゴン", gen: 8, types: ["いわ", "ほのお"] },
    { name: "セキタンザン", gen: 8, types: ["いわ", "ほのお"] },
    { name: "セキタンザン(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["いわ", "ほのお"] },
    { name: "カジッチュ", gen: 8, types: ["くさ", "ドラゴン"] },
    { name: "アップリュー", gen: 8, types: ["くさ", "ドラゴン"] },
    { name: "アップリュー(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["くさ", "ドラゴン"] },
    { name: "タルップル", gen: 8, types: ["くさ", "ドラゴン"] },
    { name: "タルップル(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["くさ", "ドラゴン"] },
    { name: "スナヘビ", gen: 8, types: ["じめん"] },
    { name: "サダイジャ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["じめん"] },
    { name: "ウッウ", gen: 8, types: ["ひこう", "みず"] },
    { name: "サシカマス", gen: 8, types: ["みず"] },
    { name: "カマスジョー", gen: 8, types: ["みず"] },
    { name: "エレズン", gen: 8, types: ["でんき", "どく"] },
    { name: "ストリンダー(ハイなすがた)", gen: 8, types: ["でんき", "どく"] },
    { name: "ストリンダー(ハイなすがた・キョダイマックスのすがた)", gen: "キョダイマックス", types: ["でんき", "どく"] },
    { name: "ストリンダー(ローなすがた)", gen: 8, types: ["でんき", "どく"] },
    { name: "ストリンダー(ローなすがた・キョダイマックスのすがた)", gen: "キョダイマックス", types: ["でんき", "どく"] },
    { name: "ヤクデ", gen: 8, types: ["ほのお", "むし"] },
    { name: "マルヤクデ", gen: 8, types: ["ほのお", "むし"] },
    { name: "マルヤクデ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["ほのお", "むし"] },
    { name: "タタッコ", gen: 8, types: ["かくとう"] },
    { name: "オトスパス", gen: 8, types: ["かくとう"] },
    { name: "ヤバチャ(がんさくフォルム)", gen: 8, types: ["ゴースト"] },
    { name: "ヤバチャ(しんさくフォルム)", gen: 8, types: ["ゴースト"] },
    { name: "ポットデス(がんさくフォルム)", gen: 8, types: ["ゴースト"] },
    { name: "ポットデス(しんさくフォルム)", gen: 8, types: ["ゴースト"] },
    { name: "ミブリム", gen: 8, types: ["エスパー"] },
    { name: "テブリム", gen: 8, types: ["エスパー"] },
    { name: "ブリムオン", gen: 8, types: ["エスパー", "フェアリー"] },
    { name: "ブリムオン(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["エスパー", "フェアリー"] },
    { name: "ベロバー", gen: 8, types: ["あく", "フェアリー"] },
    { name: "ギモー", gen: 8, types: ["あく", "フェアリー"] },
    { name: "オーロンゲ", gen: 8, types: ["あく", "フェアリー"] },
    { name: "オーロンゲ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["あく", "フェアリー"] },
    { name: "タチフサグマ", gen: 8, types: ["あく", "ノーマル"] },
    { name: "ニャイキング", gen: 8, types: ["はがね"] },
    { name: "サニゴーン", gen: 8, types: ["ゴースト"] },
    { name: "ネギガナイト", gen: 8, types: ["かくとう"] },
    { name: "バリコオル", gen: 8, types: ["こおり", "エスパー"] },
    { name: "デスバーン", gen: 8, types: ["じめん", "ゴースト"] },
    { name: "マホミル", gen: 8, types: ["フェアリー"] },
    { name: "マホイップ", gen: 8, types: ["フェアリー"] },
    { name: "マホイップ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["フェアリー"] },
    { name: "タイレーツ", gen: 8, types: ["かくとう"] },
    { name: "メガタイレーツ", gen: "メガシンカ", types: ["かくとう"] },
    { name: "バチンウニ", gen: 8, types: ["でんき"] },
    { name: "ユキハミ", gen: 8, types: ["こおり", "むし"] },
    { name: "モスノウ", gen: 8, types: ["こおり", "むし"] },
    { name: "イシヘンジン", gen: 8, types: ["いわ"] },
    { name: "コオリッポ(アイスフェイス)", gen: 8, types: ["こおり"] },
    { name: "コオリッポ(ナイスフェイス)", gen: 8, types: ["こおり"] },
    { name: "イエッサン(オスのすがた)", gen: 8, types: ["エスパー", "ノーマル"] },
    { name: "イエッサン(メスのすがた)", gen: 8, types: ["エスパー", "ノーマル"] },
    { name: "モルペコ(まんぷくもよう)", gen: 8, types: ["でんき", "あく"] },
    { name: "モルペコ(はらぺこもよう)", gen: 8, types: ["でんき", "あく"] },
    { name: "ゾウドウ", gen: 8, types: ["はがね"] },
    { name: "ダイオウドウ", gen: 8, types: ["はがね"] },
    { name: "ダイオウドウ(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["はがね"] },
    { name: "パッチラゴン", gen: 8, types: ["でんき", "ドラゴン"] },
    { name: "パッチルドン", gen: 8, types: ["でんき", "こおり"] },
    { name: "ウオノラゴン", gen: 8, types: ["みず", "ドラゴン"] },
    { name: "ウオチルドン", gen: 8, types: ["みず", "こおり"] },
    { name: "ジュラルドン", gen: 8, types: ["はがね", "ドラゴン"] },
    { name: "ジュラルドン(キョダイマックスのすがた)", gen: "キョダイマックス", types: ["はがね", "ドラゴン"] },
    { name: "ドラメシヤ", gen: 8, types: ["ドラゴン", "ゴースト"] },
    { name: "ドロンチ", gen: 8, types: ["ドラゴン", "ゴースト"] },
    { name: "ドラパルト", gen: 8, types: ["ドラゴン", "ゴースト"] },
    { name: "ザシアン(れきせんのゆうしゃ)", gen: 8, types: ["フェアリー"] },
    { name: "ザシアン(けんのおう)", gen: 8, types: ["フェアリー", "はがね"] },
    { name: "ザマゼンタ(れきせんのゆうしゃ)", gen: 8, types: ["かくとう"] },
    { name: "ザマゼンタ(たてのおう)", gen: 8, types: ["かくとう", "はがね"] },
    { name: "ムゲンダイナ", gen: 8, types: ["どく", "ドラゴン"] },
    { name: "ダクマ", gen: 8, types: ["かくとう"] },
    { name: "ウーラオス(いちげきのかた)", gen: 8, types: ["かくとう", "あく"] },
    { name: "ウーラオス(いちげきのかた・キョダイマックスのすがた)", gen: "キョダイマックス", types: ["かくとう", "あく"] },
    { name: "ウーラオス(れんげきのかた)", gen: 8, types: ["かくとう", "みず"] },
    { name: "ウーラオス(れんげきのかた・キョダイマックスのすがた)", gen: "キョダイマックス", types: ["かくとう", "みず"] },
    { name: "ザルード", gen: 8, types: ["あく", "くさ"] },
    { name: "レジエレキ", gen: 8, types: ["でんき"] },
    { name: "レジドラゴ", gen: 8, types: ["ドラゴン"] },
    { name: "ブリザポス", gen: 8, types: ["こおり"] },
    { name: "レイスポス", gen: 8, types: ["ゴースト"] },
    { name: "バドレックス", gen: 8, types: ["エスパー", "くさ"] },
    { name: "バドレックス(はくばじょうのすがた)", gen: 8, types: ["エスパー", "こおり"] },
    { name: "バドレックス(こくばじょうのすがた)", gen: 8, types: ["エスパー", "ゴースト"] },
    { name: "アヤシシ", gen: 8, types: ["ノーマル", "エスパー"] },
    { name: "バサギリ", gen: 8, types: ["むし", "いわ"] },
    { name: "ガチグマ", gen: 8, types: ["じめん", "ノーマル"] },
    { name: "ガチグマ(アカツキ)", gen: 8, types: ["じめん", "ノーマル"] },
    { name: "イダイトウ(オスのすがた)", gen: 8, types: ["みず", "ゴースト"] },
    { name: "オオニューラ(メスのすがた)", gen: 8, types: ["かくとう", "どく"] },
    { name: "ハリーマン", gen: 8, types: ["あく", "どく"] },
    { name: "ラブトロス(けしんフォルム)", gen: 8, types: ["フェアリー", "ひこう"] },
    { name: "ラブトロス(れいじゅうフォルム)", gen: 8, types: ["フェアリー", "ひこう"] },
    { name: "ニャオハ", gen: 9, types: ["くさ"] },
    { name: "ニャローテ", gen: 9, types: ["くさ"] },
    { name: "マスカーニャ", gen: 9, types: ["くさ", "あく"] },
    { name: "ホゲータ", gen: 9, types: ["ほのお"] },
    { name: "アチゲータ", gen: 9, types: ["ほのお"] },
    { name: "ラウドボーン", gen: 9, types: ["ほのお", "ゴースト"] },
    { name: "クワッス", gen: 9, types: ["みず"] },
    { name: "ウェルカモ", gen: 9, types: ["みず"] },
    { name: "ウェーニバル", gen: 9, types: ["みず", "かくとう"] },
    { name: "グルトン", gen: 9, types: ["ノーマル"] },
    { name: "パフュートン(オスのすがた)", gen: 9, types: ["ノーマル"] },
    { name: "パフュートン(メスのすがた)", gen: 9, types: ["ノーマル"] },
    { name: "タマンチュラ", gen: 9, types: ["むし"] },
    { name: "ワナイダー", gen: 9, types: ["むし"] },
    { name: "マメバッタ", gen: 9, types: ["むし"] },
    { name: "エクスレッグ", gen: 9, types: ["むし", "あく"] },
    { name: "パモ", gen: 9, types: ["でんき"] },
    { name: "パモット", gen: 9, types: ["でんき", "かくとう"] },
    { name: "パーモット", gen: 9, types: ["でんき", "かくとう"] },
    { name: "ワッカネズミ", gen: 9, types: ["ノーマル"] },
    { name: "イッカネズミ(３びきかぞく)", gen: 9, types: ["ノーマル"] },
    { name: "イッカネズミ(４ひきかぞく)", gen: 9, types: ["ノーマル"] },
    { name: "パピモッチ", gen: 9, types: ["フェアリー"] },
    { name: "バウッツェル", gen: 9, types: ["フェアリー"] },
    { name: "ミニーブ", gen: 9, types: ["くさ", "ノーマル"] },
    { name: "オリーニョ", gen: 9, types: ["くさ", "ノーマル"] },
    { name: "オリーヴァ", gen: 9, types: ["くさ", "ノーマル"] },
    { name: "イキリンコ(グリーンフェザー)", gen: 9, types: ["ノーマル", "ひこう"] },
    { name: "イキリンコ(ブルーフェザー)", gen: 9, types: ["ノーマル", "ひこう"] },
    { name: "イキリンコ(イエローフェザー)", gen: 9, types: ["ノーマル", "ひこう"] },
    { name: "イキリンコ(ホワイトフェザー)", gen: 9, types: ["ノーマル", "ひこう"] },
    { name: "コジオ", gen: 9, types: ["いわ"] },
    { name: "ジオヅム", gen: 9, types: ["いわ"] },
    { name: "キョジオーン", gen: 9, types: ["いわ"] },
    { name: "カルボウ", gen: 9, types: ["ほのお"] },
    { name: "グレンアルマ", gen: 9, types: ["ほのお", "エスパー"] },
    { name: "ソウブレイズ", gen: 9, types: ["ほのお", "ゴースト"] },
    { name: "ズピカ", gen: 9, types: ["でんき"] },
    { name: "ハラバリー", gen: 9, types: ["でんき"] },
    { name: "カイデン", gen: 9, types: ["でんき", "ひこう"] },
    { name: "タイカイデン", gen: 9, types: ["でんき", "ひこう"] },
    { name: "オラチフ", gen: 9, types: ["あく"] },
    { name: "マフィティフ", gen: 9, types: ["あく"] },
    { name: "シルシュルー", gen: 9, types: ["どく", "ノーマル"] },
    { name: "タギングル", gen: 9, types: ["どく", "ノーマル"] },
    { name: "アノクサ", gen: 9, types: ["くさ", "ゴースト"] },
    { name: "アノホラグサ", gen: 9, types: ["くさ", "ゴースト"] },
    { name: "ノノクラゲ", gen: 9, types: ["じめん", "くさ"] },
    { name: "リククラゲ", gen: 9, types: ["じめん", "くさ"] },
    { name: "ガケガニ", gen: 9, types: ["いわ"] },
    { name: "カプサイジ", gen: 9, types: ["くさ"] },
    { name: "スコヴィラン", gen: 9, types: ["くさ", "ほのお"] },
    { name: "メガスコヴィラン", gen: "メガシンカ", types: ["くさ", "ほのお"] },
    { name: "シガロコ", gen: 9, types: ["むし"] },
    { name: "ベラカス", gen: 9, types: ["むし", "エスパー"] },
    { name: "ヒラヒナ", gen: 9, types: ["エスパー"] },
    { name: "クエスパトラ", gen: 9, types: ["エスパー"] },
    { name: "カヌチャン", gen: 9, types: ["フェアリー", "はがね"] },
    { name: "ナカヌチャン", gen: 9, types: ["フェアリー", "はがね"] },
    { name: "デカヌチャン", gen: 9, types: ["フェアリー", "はがね"] },
    { name: "ウミディグダ", gen: 9, types: ["みず"] },
    { name: "ウミトリオ", gen: 9, types: ["みず"] },
    { name: "オトシドリ", gen: 9, types: ["ひこう", "あく"] },
    { name: "ナミイルカ", gen: 9, types: ["みず"] },
    { name: "イルカマン(ナイーブフォルム)", gen: 9, types: ["みず"] },
    { name: "イルカマン(マイティフォルム)", gen: 9, types: ["みず"] },
    { name: "ブロロン", gen: 9, types: ["はがね", "どく"] },
    { name: "ブロロローム", gen: 9, types: ["はがね", "どく"] },
    { name: "モトトカゲ", gen: 9, types: ["ドラゴン", "ノーマル"] },
    { name: "ミミズズ", gen: 9, types: ["はがね"] },
    { name: "キラーメ", gen: 9, types: ["いわ", "どく"] },
    { name: "キラフロル", gen: 9, types: ["いわ", "どく"] },
    { name: "メガキラフロル", gen: "メガシンカ", types: ["いわ", "どく"] },
    { name: "ボチ", gen: 9, types: ["ゴースト"] },
    { name: "ハカドッグ", gen: 9, types: ["ゴースト"] },
    { name: "カラミンゴ", gen: 9, types: ["ひこう", "かくとう"] },
    { name: "アルクジラ", gen: 9, types: ["こおり"] },
    { name: "ハルクジラ", gen: 9, types: ["こおり"] },
    { name: "ミガルーサ", gen: 9, types: ["みず", "エスパー"] },
    { name: "ヘイラッシャ", gen: 9, types: ["みず"] },
    { name: "シャリタツ(そったすがた)", gen: 9, types: ["ドラゴン", "みず"] },
    { name: "シャリタツ(たれたすがた)", gen: 9, types: ["ドラゴン", "みず"] },
    { name: "シャリタツ(のびたすがた)", gen: 9, types: ["ドラゴン", "みず"] },
    { name: "メガシャリタツ(そったすがた)", gen: "メガシンカ", types: ["ドラゴン", "みず"] },
    { name: "メガシャリタツ(たれたすがた)", gen: "メガシンカ", types: ["ドラゴン", "みず"] },
    { name: "メガシャリタツ(のびたすがた)", gen: "メガシンカ", types: ["ドラゴン", "みず"] },
    { name: "コノヨザル", gen: 9, types: ["かくとう", "ゴースト"] },
    { name: "ドオー", gen: 9, types: ["どく", "じめん"] },
    { name: "リキキリン", gen: 9, types: ["ノーマル", "エスパー"] },
    { name: "ノココッチ(ふたふしフォルム)", gen: 9, types: ["ノーマル"] },
    { name: "ノココッチ(みつふしフォルム)", gen: 9, types: ["ノーマル"] },
    { name: "ドドゲザン", gen: 9, types: ["あく", "はがね"] },
    { name: "イダイナキバ", gen: 9, types: ["じめん", "かくとう"] },
    { name: "サケブシッポ", gen: 9, types: ["フェアリー", "エスパー"] },
    { name: "アラブルタケ", gen: 9, types: ["くさ", "あく"] },
    { name: "ハバタクカミ", gen: 9, types: ["ゴースト", "フェアリー"] },
    { name: "チヲハウハネ", gen: 9, types: ["むし", "かくとう"] },
    { name: "スナノケガワ", gen: 9, types: ["でんき", "じめん"] },
    { name: "テツノワダチ", gen: 9, types: ["じめん", "はがね"] },
    { name: "テツノツツミ", gen: 9, types: ["こおり", "みず"] },
    { name: "テツノカイナ", gen: 9, types: ["かくとう", "でんき"] },
    { name: "テツノコウベ", gen: 9, types: ["あく", "ひこう"] },
    { name: "テツノドクガ", gen: 9, types: ["ほのお", "どく"] },
    { name: "テツノイバラ", gen: 9, types: ["いわ", "でんき"] },
    { name: "セビエ", gen: 9, types: ["ドラゴン", "こおり"] },
    { name: "セゴール", gen: 9, types: ["ドラゴン", "こおり"] },
    { name: "セグレイブ", gen: 9, types: ["ドラゴン", "こおり"] },
    { name: "メガセグレイブ", gen: "メガシンカ", types: ["ドラゴン", "こおり"] },
    { name: "コレクレー(はこフォルム)", gen: 9, types: ["ゴースト"] },
    { name: "コレクレー(とほフォルム)", gen: 9, types: ["ゴースト"] },
    { name: "サーフゴー", gen: 9, types: ["はがね", "ゴースト"] },
    { name: "チオンジェン", gen: 9, types: ["あく", "くさ"] },
    { name: "パオジアン", gen: 9, types: ["あく", "こおり"] },
    { name: "ディンルー", gen: 9, types: ["あく", "じめん"] },
    { name: "イーユイ", gen: 9, types: ["あく", "ほのお"] },
    { name: "トドロクツキ", gen: 9, types: ["ドラゴン", "あく"] },
    { name: "テツノブジン", gen: 9, types: ["フェアリー", "かくとう"] },
    { name: "コライドン", gen: 9, types: ["かくとう", "ドラゴン"] },
    { name: "ミライドン", gen: 9, types: ["でんき", "ドラゴン"] },
    { name: "ウネルミナモ", gen: 9, types: ["みず", "ドラゴン"] },
    { name: "テツノイサハ", gen: 9, types: ["くさ", "エスパー"] },
    { name: "カミッチュ", gen: 9, types: ["くさ", "ドラゴン"] },
    { name: "チャデス(マガイモノのすがた)", gen: 9, types: ["くさ", "ゴースト"] },
    { name: "チャデス(タカイモノのすがた)", gen: 9, types: ["くさ", "ゴースト"] },
    { name: "ヤバソチャ(ボンサクのすがた)", gen: 9, types: ["くさ", "ゴースト"] },
    { name: "ヤバソチャ(ケッサクのすがた)", gen: 9, types: ["くさ", "ゴースト"] },
    { name: "イイネイヌ", gen: 9, types: ["どく", "かくとう"] },
    { name: "マシマシラ", gen: 9, types: ["どく", "エスパー"] },
    { name: "キチキギス", gen: 9, types: ["どく", "フェアリー"] },
    { name: "オーガポン(みどりのめん)", gen: 9, types: ["くさ"] },
    { name: "オーガポン(いどのめん)", gen: 9, types: ["くさ", "みず"] },
    { name: "オーガポン(かまどのめん)", gen: 9, types: ["くさ", "ほのお"] },
    { name: "オーガポン(いしずえのめん)", gen: 9, types: ["くさ", "いわ"] },
    { name: "ブリジュラス", gen: 9, types: ["はがね", "ドラゴン"] },
    { name: "カミツオロチ", gen: 9, types: ["くさ", "ドラゴン"] },
    { name: "ウガツホムラ", gen: 9, types: ["ほのお", "ドラゴン"] },
    { name: "タケルライコ", gen: 9, types: ["でんき", "ドラゴン"] },
    { name: "テツノイワオ", gen: 9, types: ["いわ", "エスパー"] },
    { name: "テツノカシラ", gen: 9, types: ["はがね", "エスパー"] },
    { name: "テラパゴス(ノーマルフォルム)", gen: 9, types: ["ノーマル"] },
    { name: "テラパゴス(テラスタルフォルム)", gen: 9, types: ["ノーマル"] },
    { name: "テラパゴス(ステラフォルム)", gen: 9, types: ["ノーマル"] }
];